"""Replace weak template sentences in words.json with real contextual sentences.

A "weak" sentence matches the pattern: "The word X is fun/tricky..."
This script defines a big dict of {word: new_sentence} and merges it in.

Run: python fix-sentences.py
"""
import json
import re
from pathlib import Path

WORDS_JSON = Path(r"C:/Users/dglazier/source/Personal/mammas-place/data/spelling/words.json")

WEAK_RE = re.compile(
    r"^the (word ['\"]?\w+['\"]?|\w+) is (fun|tricky)",
    re.IGNORECASE,
)

WORD_TO_NEW_SENTENCE = {
    # L5 words
    "ample": "We had ample time to finish the game.",
    "angle": "The roof slopes at a steep angle.",
    "animal": "A horse is my favorite animal.",
    "apple": "I ate a crunchy red apple.",
    "around": "We walked around the park.",
    "autumn": "Leaves turn orange in autumn.",
    "baby": "The baby giggled at the puppy.",
    "bake": "Let's bake cookies for grandma.",
    "baked": "Mom baked a chocolate cake.",
    "baker": "The baker made fresh bread today.",
    "baking": "The kitchen smells like baking bread.",
    "better": "I feel better after a nap.",
    "bike": "I rode my bike to school.",
    "biked": "We biked along the river path.",
    "biking": "Biking down the hill was fun.",
    "bite": "Don't bite your fingernails.",
    "body": "Exercise keeps your body strong.",
    "bone": "The dog buried a big bone.",
    "bottle": "Please pass me the water bottle.",
    "bottom": "My shoe was stuck at the bottom.",
    "brother": "My brother is older than me.",
    "buddy": "Sam is my best buddy.",
    "bunny": "A soft bunny hopped past us.",
    "button": "I lost a button on my coat.",
    "buzzy": "The buzzy bee circled the flower.",
    "cage": "The parrot lives in a big cage.",
    "cake": "We had cake at the party.",
    "candy": "Grandpa gave me a piece of candy.",
    "carry": "Can you carry these books?",
    "chance": "I had one chance to win.",
    "circle": "Sit in a circle for story time.",
    "city": "The city has tall buildings.",
    "clapped": "Everyone clapped after the song.",
    "color": "Blue is my favorite color.",
    "cotton": "My shirt is made of soft cotton.",
    "crazy": "That was a crazy roller coaster.",
    "crying": "The baby was crying for milk.",
    "cube": "Drop an ice cube in my drink.",
    "daddy": "Daddy reads me a bedtime story.",
    "daisy": "She picked a white daisy.",
    "dance": "We love to dance to music.",
    "dice": "Roll the dice to start the game.",
    "dinner": "We had pizza for dinner.",
    "dirty": "My hands got dirty in the garden.",
    "dizzy": "Spinning made me feel dizzy.",
    "doing": "What are you doing today?",
    "dollar": "I saved a dollar for the store.",
    "donkey": "The donkey carried our bags.",
    "doodle": "I like to doodle in my notebook.",
    "dropped": "I dropped my pencil on the floor.",
    "during": "Stay quiet during the movie.",
    "eagle": "An eagle soared above the trees.",
    "eating": "We are eating fresh apples.",
    "either": "You can pick either toy.",
    "ended": "The game ended in a tie.",
    "face": "She had a happy face.",
    "fairy": "A tiny fairy danced in the garden.",
    "father": "My father teaches me to fish.",
    "flame": "The candle flame flickered softly.",
    "flower": "I picked a yellow flower.",
    "flying": "The kite is flying high.",
    "follow": "Please follow me to the room.",
    "forest": "We hiked through a thick forest.",
    "forget": "Don't forget your backpack.",
    "forty": "Grandma turns forty next year.",
    "found": "I found my missing sock.",
    "fourth": "Today is my fourth day at camp.",
    "frame": "I put the photo in a wooden frame.",
    "friend": "My best friend lives next door.",
    "funny": "That joke was really funny.",
    "future": "In the future I want to be a vet.",
    "fuzzy": "The kitten has fuzzy fur.",
    "game": "We played a board game.",
    "gather": "Let's gather around the fire.",
    "gentle": "Be gentle with the puppy.",
    "giggle": "The babies giggle when tickled.",
    "going": "We are going to the park.",
    "grand": "The piano made a grand sound.",
    "guess": "Can you guess my number?",
    "hammer": "Use the hammer to fix the chair.",
    "happen": "What will happen next?",
    "happy": "I am happy to see you.",
    "hardly": "I could hardly hear the whisper.",
    "heavy": "This box is too heavy to lift.",
    "hello": "She waved and said hello.",
    "hidden": "The treasure was hidden in the chest.",
    "hike": "Let's hike up the mountain.",
    "hiked": "We hiked all morning.",
    "hiking": "Hiking is my favorite activity.",
    "hobby": "Drawing is my favorite hobby.",
    "home": "We walked home after school.",
    "honey": "Bears love sweet honey.",
    "hope": "I hope it doesn't rain today.",
    "hoped": "I hoped to see my cousin.",
    "hoping": "We are hoping for snow.",
    "hopped": "The frog hopped into the pond.",
    "hopping": "The bunny is hopping around the yard.",
    "hundred": "There are a hundred kids at school.",
    "hungry": "I am hungry for lunch.",
    "hurry": "Hurry or we'll miss the bus.",
    "ice": "The pond was covered in ice.",
    "ideal": "It was an ideal day for a picnic.",
    "inside": "Let's go inside the house.",
    "instead": "Have water instead of soda.",
    "island": "We sailed to a tiny island.",
    "jumped": "The cat jumped onto the sofa.",
    "kindly": "She kindly held the door for me.",
    "kite": "My kite flew high in the sky.",
    "kitten": "The kitten chased a string.",
    "knife": "Use a knife to slice the bread.",
    "ladder": "Dad climbed the ladder to the roof.",
    "lake": "We swam in the cool lake.",
    "language": "Spanish is a beautiful language.",
    "laughter": "Their laughter filled the room.",
    "lazy": "I felt lazy on Saturday morning.",
    "letter": "Grandma sent me a long letter.",
    "life": "Life on the farm is busy.",
    "liked": "I liked the chocolate cookies.",
    "little": "A little mouse ran by.",
    "looked": "He looked under the bed.",
    "looking": "She is looking for her shoes.",
    "lucky": "I felt lucky to find a penny.",
    "magic": "The magician did a magic trick.",
    "make": "Let's make a sandcastle.",
    "maple": "The maple tree turned bright red.",
    "market": "Mom buys fruit at the market.",
    "matter": "It doesn't matter who wins.",
    "meaning": "I don't know the meaning of that word.",
    "merry": "We sang a merry tune.",
    "mice": "Two mice ran across the floor.",
    "middle": "Sit in the middle of the bench.",
    "mile": "We walked a whole mile.",
    "million": "The sky has a million stars.",
    "minute": "Wait one minute, please.",
    "mister": "Mister Jones is our neighbor.",
    "mitten": "I lost my red mitten in the snow.",
    "model": "He built a model airplane.",
    "mommy": "Mommy tucked me into bed.",
    "monkey": "The monkey swung from the branch.",
    "morning": "I drink milk every morning.",
    "mother": "My mother makes the best pancakes.",
    "mountain": "We climbed a tall mountain.",
    "muffin": "I had a blueberry muffin for breakfast.",
    "name": "My name is Lily.",
    "nature": "I love being out in nature.",
    "neighbor": "Our neighbor waved hello.",
    "nice": "It was nice to see you.",
    "noodle": "I slurped one long noodle.",
    "note": "I left a note on the fridge.",
    "nothing": "There is nothing left in the bowl.",
    "number": "Pick a number between one and ten.",
    "office": "Dad works in a small office.",
    "outside": "Let's play outside in the snow.",
    "paddle": "Use the paddle to row the boat.",
    "page": "Turn to the next page.",
    "painted": "She painted a sunny picture.",
    "painter": "The painter made the walls blue.",
    "paper": "Write your name on the paper.",
    "parent": "Each kid brought a parent to school.",
    "party": "Her birthday party was so fun.",
    "pencil": "My pencil needs a new point.",
    "perhaps": "Perhaps we'll go to the zoo.",
    "picture": "I drew a picture of my dog.",
    "pillow": "I hugged my soft pillow.",
    "planet": "Earth is our home planet.",
    "planted": "We planted seeds in the garden.",
    "played": "We played tag at recess.",
    "playing": "The kids are playing in the yard.",
    "plenty": "There is plenty of pizza for everyone.",
    "pocket": "I put a coin in my pocket.",
    "poodle": "Her fluffy poodle loves to run.",
    "pretty": "The garden looks very pretty.",
    "problem": "I solved the math problem.",
    "puppy": "Our puppy chewed my shoe.",
    "purple": "Grapes are juicy and purple.",
    "puzzle": "We finished the jigsaw puzzle.",
    "question": "I have a question for the teacher.",
    "quickly": "The dog ran quickly after the ball.",
    "quiet": "Please be quiet in the library.",
    "race": "I won the running race.",
    "rage": "He yelled with rage when he lost.",
    "rake": "I used a rake on the leaves.",
    "reading": "I love reading bedtime stories.",
    "reason": "Tell me the reason you are late.",
    "ribbon": "She tied a pink ribbon in her hair.",
    "rice": "We had chicken and rice for dinner.",
    "riding": "He is riding his new scooter.",
    "river": "The river flows past our house.",
    "rocket": "The rocket blasted into space.",
    "rope": "We jumped over the long rope.",
    "rose": "I picked a red rose for mom.",
    "rude": "It is rude to interrupt.",
    "rule": "The first rule is to be kind.",
    "running": "We are running to the bus.",
    "saddle": "I put the saddle on the horse.",
    "safe": "Stay safe on your bike.",
    "safety": "Wear a helmet for safety.",
    "sample": "Try a sample of the cheese.",
    "second": "Wait one more second.",
    "seven": "I am seven years old.",
    "simple": "This puzzle is simple to solve.",
    "singing": "The birds were singing at dawn.",
    "sister": "My sister braids my hair.",
    "sitting": "She is sitting on the porch.",
    "skating": "We went skating on the pond.",
    "slowly": "The turtle moved slowly across the path.",
    "smaller": "My foot is smaller than yours.",
    "smiled": "She smiled when I waved.",
    "someone": "Someone left a hat on the bench.",
    "something": "I have something to tell you.",
    "sometimes": "Sometimes we go camping.",
    "sorry": "I am sorry I broke your toy.",
    "spring": "Flowers bloom in the spring.",
    "squirrel": "A squirrel ran up the oak tree.",
    "station": "We waited at the train station.",
    "stone": "I skipped a stone across the lake.",
    "stopped": "The car stopped at the red light.",
    "story": "Read me one more story, please.",
    "strange": "I heard a strange noise outside.",
    "student": "Every student got a sticker.",
    "subject": "Math is my favorite subject.",
    "sudden": "A sudden gust blew my hat off.",
    "suddenly": "Suddenly the lights went out.",
    "summer": "We swim every day in summer.",
    "sunny": "It was a warm, sunny day.",
    "supper": "We had soup for supper.",
    "suppose": "I suppose you are right.",
    "table": "Set the plates on the table.",
    "take": "Take an umbrella with you.",
    "talked": "We talked all afternoon.",
    "talking": "Stop talking during the movie.",
    "teddy": "I sleep with my teddy bear.",
    "temple": "We visited an ancient temple.",
    "thunder": "The thunder shook the windows.",
    "tiger": "A tiger has orange stripes.",
    "together": "We worked together on the project.",
    "traffic": "Traffic was slow this morning.",
    "travel": "I love to travel to new places.",
    "trouble": "Don't get into trouble at school.",
    "trying": "I am trying to ride a bike.",
    "tube": "Squeeze the tube of toothpaste.",
    "tune": "She hummed a happy tune.",
    "turkey": "We ate turkey for Thanksgiving.",
    "twenty": "There were twenty kids at the party.",
    "uncle": "My uncle taught me to fish.",
    "under": "The cat hid under the bed.",
    "unless": "We won't leave unless you come.",
    "until": "Stay here until I come back.",
    "village": "A small village sits by the river.",
    "visit": "We visit grandma every Sunday.",
    "voice": "Use your inside voice, please.",
    "waited": "We waited an hour for the bus.",
    "waiting": "I am waiting for my turn.",
    "wake": "Wake up, it's morning!",
    "walked": "We walked all the way home.",
    "walking": "Walking helps me think.",
    "water": "Please pour me some water.",
    "wife": "The farmer's wife baked pies.",
    "wiggle": "Wiggle your toes in the sand.",
    "window": "I looked out the window at the rain.",
    "winter": "We build snowmen in winter.",
    "without": "Don't leave without your coat.",
    "woman": "A kind woman helped us.",
    "women": "Three women were singing on stage.",
    "worry": "Don't worry, I will help you.",
    "written": "She has written a long letter.",
    "yellow": "The school bus is bright yellow.",

    # L6 words
    "absence": "Her absence was noticed at school.",
    "accept": "Please accept this gift from me.",
    "access": "Only adults have access to the safe.",
    "accident": "It was an accident, not on purpose.",
    "accidentally": "I accidentally spilled the milk.",
    "accommodate": "The hotel can accommodate ten guests.",
    "accuse": "Don't accuse him without proof.",
    "achieve": "You can achieve great things.",
    "acknowledge": "He nodded to acknowledge my answer.",
    "acquire": "Squirrels acquire nuts for winter.",
    "across": "We ran across the field.",
    "active": "An active puppy needs lots of play.",
    "actually": "I actually liked the new flavor.",
    "address": "Write your address on the envelope.",
    "advice": "Grandma gave me good advice.",
    "afraid": "I was afraid of the dark.",
    "afternoon": "We had a picnic in the afternoon.",
    "against": "Lean the bike against the wall.",
    "agree": "I agree with your idea.",
    "ahead": "Look ahead before crossing the street.",
    "airplane": "The airplane flew above the clouds.",
    "allowed": "We are allowed to stay up late.",
    "almost": "It is almost dinner time.",
    "alone": "I don't like to walk alone at night.",
    "along": "We walked along the river.",
    "already": "I already finished my homework.",
    "although": "I went outside although it was raining.",
    "altogether": "There were ten of us altogether.",
    "amateur": "He is an amateur photographer.",
    "amount": "Add a small amount of sugar.",
    "ancient": "We saw ancient ruins on the trip.",
    "angry": "I felt angry when my toy broke.",
    "answer": "Please answer the teacher's question.",
    "anybody": "Is anybody home?",
    "anyone": "Anyone can join the game.",
    "anything": "I would do anything to help.",
    "anywhere": "We can sit anywhere we want.",
    "apparent": "It was apparent that he was tired.",
    "appear": "Stars appear at night.",
    "appearance": "She changed her appearance with a haircut.",
    "appreciate": "I appreciate your help.",
    "April": "My birthday is in April.",
    "argument": "They had a small argument over the game.",
    "arrive": "We will arrive by noon.",
    "asleep": "The baby fell asleep in the car.",
    "atheist": "An atheist does not believe in God.",
    "August": "School starts in late August.",
    "author": "The author signed my book.",
    "autumn": "Pumpkins ripen in the autumn.",
    "awful": "The spoiled milk smelled awful.",
    "awkward": "I felt awkward at the new school.",
    "balance": "She can balance on one foot.",
    "balloon": "I tied a red balloon to the chair.",
    "banana": "I peeled a yellow banana.",
    "basically": "It is basically just a big game.",
    "basket": "The basket was full of apples.",
    "battle": "Soldiers fought a long battle.",
    "beauty": "The mountain's beauty took my breath away.",
    "become": "I want to become a teacher.",
    "beginning": "The beginning of the story is exciting.",
    "behavior": "Her behavior at the party was kind.",
    "behaviour": "Their behaviour at the museum was polite.",
    "behind": "The cat is hiding behind the chair.",
    "below": "The submarine dove below the waves.",
    "beside": "Sit beside me at the table.",
    "between": "Stand between your sister and me.",
    "biscuit": "I had a warm biscuit with jam.",
    "blanket": "I curled up under a cozy blanket.",
    "borrow": "May I borrow your pencil?",
    "bother": "Don't bother your brother while he reads.",
    "bought": "We bought ice cream at the store.",
    "bridge": "We drove across the long bridge.",
    "bright": "The sun was very bright today.",
    "broken": "My toy car is broken.",
    "brought": "She brought cookies to share.",
    "building": "The tall building has many windows.",
    "business": "Mom runs a small business.",
    "calendar": "I marked my birthday on the calendar.",
    "captain": "The captain steered the ship.",
    "careful": "Be careful crossing the street.",
    "carrot": "The bunny nibbled on a carrot.",
    "castle": "We built a sandcastle on the beach.",
    "category": "Apples belong in the fruit category.",
    "ceiling": "A spider hung from the ceiling.",
    "cemetery": "We left flowers at the cemetery.",
    "central": "The park is in the central part of town.",
    "century": "A century is one hundred years.",
    "certain": "I am certain I locked the door.",
    "changeable": "The weather is changeable today.",
    "channel": "Please change the TV channel.",
    "chapter": "I read one chapter before bed.",
    "charge": "Plug it in to charge the battery.",
    "chief": "The fire chief gave a safety talk.",
    "chimney": "Smoke rose from the chimney.",
    "collectible": "That old coin is a rare collectible.",
    "column": "She read the funny newspaper column.",
    "committed": "He committed to practicing every day.",
    "completely": "I completely forgot my lunchbox.",
    "concede": "I had to concede the game to her.",
    "consensus": "We reached a consensus on the rules.",
    "controversy": "There was controversy over the call.",
    "convenient": "It is convenient to live near school.",
    "courteous": "Please be courteous to guests.",
    "criticize": "Don't criticize before you try.",
    "deceive": "A magician can deceive the eye.",
    "deficit": "The team had a deficit at halftime.",
    "describe": "Describe what the puppy looked like.",
    "desperate": "He was desperate for a glass of water.",
    "discipline": "Practicing piano takes discipline.",
    "drunkenness": "Drunkenness is not allowed at the park.",
    "embarrass": "Don't embarrass me in front of my friends.",
    "equipment": "Pack the camping equipment in the car.",
    "exhilarate": "Roller coasters always exhilarate me.",
    "existence": "Dinosaurs once roamed in existence.",
    "experience": "Camping was a fun experience.",
    "explanation": "She gave a clear explanation.",
    "fascinating": "Outer space is fascinating to learn about.",
    "fiery": "The dragon had a fiery breath.",
    "foreign": "Spanish is a foreign language to me.",
    "foreseeable": "We'll be friends for the foreseeable future.",
    "forty": "There are forty pages in this book.",
    "fulfill": "I will fulfill my promise.",
    "gauge": "Check the gas gauge before driving.",
    "genealogy": "Grandpa studies our family genealogy.",
    "generally": "Cats generally don't like baths.",
    "government": "Our government has three branches.",
    "grateful": "I am grateful for my family.",
    "guarantee": "I guarantee you will love this book.",
    "guidance": "I ask my parents for guidance.",
    "harass": "Don't harass the dog while he eats.",
    "height": "Mark your height on the wall.",
    "hierarchy": "Ants live in a strict hierarchy.",
    "humorous": "Her story was very humorous.",
    "hygiene": "Brushing teeth is good hygiene.",
    "hypocrisy": "Saying one thing and doing another is hypocrisy.",
    "ignorance": "Ignorance of the rule is no excuse.",
    "imitate": "Parrots can imitate human voices.",
    "immediate": "We need an immediate answer.",
    "incidentally": "Incidentally, I saw your sister today.",
    "independent": "She is an independent reader now.",
    "indispensable": "Water is indispensable to life.",
    "inoculate": "The doctor will inoculate the puppy.",
    "intelligence": "Dolphins show great intelligence.",
    "jealous": "He was jealous of his brother's new bike.",
    "judgment": "The judge made a fair judgment.",
    "knowledge": "Books are full of knowledge.",
    "leisure": "Reading is a leisure activity I love.",
    "liaison": "She is the liaison between the two teams.",
    "library": "I borrowed three books from the library.",
    "license": "Mom got her driver's license at sixteen.",
    "lightning": "Lightning lit up the night sky.",
    "maintenance": "The bike needs some maintenance.",
    "maneuver": "He had to maneuver the car into the spot.",
    "medieval": "Knights lived in medieval times.",
    "memento": "I keep a shell as a memento of the beach.",
    "millennium": "A millennium is a thousand years.",
    "miniature": "She collects miniature horse figures.",
    "minuscule": "An ant looks minuscule next to a dog.",
    "mischievous": "The mischievous puppy stole my sock.",
    "misspell": "Try not to misspell your own name.",
    "mortgage": "My parents pay a mortgage on the house.",
    "neighbor": "Our neighbor lent us some sugar.",
    "noticeable": "The stain on the rug was noticeable.",
    "occasion": "Her birthday was a special occasion.",
    "occurrence": "Snow in May is a rare occurrence.",
    "official": "The referee made the call official.",
    "originally": "I originally wanted the blue one.",
    "outrageous": "That clown's hat was outrageous.",
    "parallel": "The two train tracks ran parallel.",
    "paralyze": "Fear can paralyze you for a moment.",
    "particular": "He is particular about his toys.",
    "pastime": "Fishing is a fun pastime.",
    "perceive": "I perceive a sweet smell from the kitchen.",
    "perform": "The band will perform tonight.",
    "permanent": "Use a pencil, not a permanent marker.",
    "personnel": "Hospital personnel wear name badges.",
    "persuade": "I tried to persuade her to come along.",
    "playwright": "Shakespeare was a famous playwright.",
    "possess": "I possess only a few coins.",
    "possession": "The ring was her most prized possession.",
    "precede": "An appetizer can precede the main meal.",
    "preference": "My preference is chocolate ice cream.",
    "prejudice": "We should treat everyone without prejudice.",
    "prevalent": "Colds are prevalent in winter.",
    "principal": "The principal greeted us at the door.",
    "principle": "Honesty is an important principle.",
    "privilege": "It is a privilege to read with you.",
    "pronunciation": "I practiced the word's pronunciation.",
    "publicly": "She thanked her team publicly.",
    "questionnaire": "We filled out a short questionnaire.",
    "recommend": "I recommend this storybook.",
    "reference": "He used a reference book for the report.",
    "referred": "The doctor referred us to a specialist.",
    "relevant": "Please only share relevant information.",
    "relieve": "A cool drink will relieve the heat.",
    "religious": "She is religious and prays each night.",
    "remembrance": "We planted a tree in remembrance of grandpa.",
    "reservoir": "The reservoir holds our drinking water.",
    "restaurant": "We ate dinner at a new restaurant.",
    "rhyme": "Cat and hat rhyme.",
    "schedule": "Check the schedule for the next bus.",
    "scissors": "Use safety scissors to cut the paper.",
    "secretary": "The secretary answered the phone.",
    "siege": "The castle was under siege for weeks.",
    "similar": "Our shoes look very similar.",
    "sincerely": "I sincerely thank you for the gift.",
    "skillful": "She is a skillful piano player.",
    "sophomore": "My cousin is a sophomore in high school.",
    "souvenir": "I bought a magnet as a souvenir.",
    "specifically": "I asked specifically for blueberry pancakes.",
    "successful": "Her bake sale was very successful.",
    "supersede": "New rules supersede the old ones.",
    "surprise": "Her gift was a wonderful surprise.",
    "thorough": "He did a thorough job cleaning his room.",
    "threshold": "She paused at the threshold of the door.",
    "tomorrow": "We are going swimming tomorrow.",
    "twelfth": "Today is the twelfth of June.",
    "tyranny": "The people fought against tyranny.",
    "underrate": "Don't underrate a small kindness.",
    "until": "We played until the sun went down.",
    "vacuum": "Mom will vacuum the rug today.",
    "various": "The store sells various kinds of candy.",
    "vegetable": "Carrots are a healthy vegetable.",
    "vicious": "The vicious wind knocked down a tree.",
    "view": "We had a great view from the hill.",
    "village": "Our cabin sits in a small village.",
    "warrant": "The police had a warrant to search.",
    "weather": "The weather is warm and sunny.",
    "Wednesday": "We have art class on Wednesday.",
    "welcome": "You are always welcome at our house.",
    "whether": "I can't decide whether to bring a coat.",
    "whisper": "Please whisper in the library.",
    "whole": "I ate the whole apple.",
    "yacht": "We sailed on a small yacht.",

    # L2 words (matched second weak template: "The X is fun to say")
    "back": "I lay flat on my back.",
    "begun": "The race has begun.",
    "bet": "I bet you can't catch me.",
    "black": "The crow has black feathers.",
    "blame": "Don't blame me for the mess.",
    "blot": "A blot of ink stained the page.",
    "bold": "He made a bold leap into the pool.",
    "brake": "Press the brake to stop the bike.",
    "bride": "The bride wore a long white dress.",
    "buck": "A buck has antlers on its head.",
    "came": "She came home from school.",
    "chop": "Help me chop the carrots.",
    "click": "I heard the door click shut.",
    "clot": "A clot stopped the bleeding cut.",
    "cluck": "Hens cluck when they lay eggs.",
    "crack": "There is a crack in the cup.",
    "crate": "We packed apples into the crate.",
    "crop": "The farmer harvested the corn crop.",
    "dame": "The kind dame served us tea.",
    "date": "What date is your birthday?",
    "debt": "He paid off his debt last year.",
    "dine": "We dine together every Sunday.",
    "fame": "The singer rose to fame quickly.",
    "fate": "Their fate was to be best friends.",
    "fine": "I feel fine after a nap.",
    "flake": "A single snow flake landed on my nose.",
    "flock": "A flock of birds flew south.",
    "flop": "I watched the fish flop on deck.",
    "fold": "Help me fold the laundry.",
    "fret": "Don't fret about the test.",
    "glide": "Eagles glide on the wind.",
    "grin": "She had a big grin on her face.",
    "hate": "I hate when my ice cream melts.",
    "jet": "The jet flew above the clouds.",
    "kick": "Try to kick the ball into the goal.",
    "lame": "His joke was a little lame.",
    "late": "Don't be late for school.",
    "lick": "The puppy gave me a lick.",
    "line": "Stand in a straight line.",
    "lock": "Make sure to lock the door.",
    "luck": "Good luck on your test.",
    "mate": "Penguins find a mate for life.",
    "mine": "That book is mine.",
    "mold": "Old bread can grow mold.",
    "muck": "My boots were covered in muck.",
    "nine": "Nine kids came to the party.",
    "pack": "Pack your bag for the trip.",
    "pick": "Pick a card, any card.",
    "pine": "A tall pine tree stood by the cabin.",
    "plop": "I heard the rock plop into the pond.",
    "plot": "Tell me the plot of the movie.",
    "pluck": "She likes to pluck the guitar strings.",
    "pride": "I felt pride when I finished my book.",
    "prop": "Use this stick to prop open the door.",
    "puck": "The hockey puck slid across the ice.",
    "quack": "The duck began to quack loudly.",
    "rack": "Hang your coat on the rack.",
    "rate": "The runner kept a steady rate.",
    "sack": "He carried a sack of potatoes.",
    "same": "We wore the same shirt today.",
    "scold": "Mom doesn't like to scold us.",
    "shack": "We built a tiny shack in the yard.",
    "shake": "Don't shake the soda can.",
    "shame": "I felt shame after breaking the lamp.",
    "shin": "I bumped my shin on the chair.",
    "shine": "The stars shine at night.",
    "shock": "The loud noise gave me a shock.",
    "shun": "Bees shun the rain.",
    "sick": "I stayed home because I was sick.",
    "side": "Sit by my side at lunch.",
    "skin": "The apple has a red skin.",
    "slate": "The slate roof kept us dry.",
    "slot": "Put the coin in the slot.",
    "sock": "I lost one fuzzy sock in the dryer.",
    "sold": "We sold lemonade on the corner.",
    "spine": "Stand tall and straighten your spine.",
    "sprig": "Mom added a sprig of mint to the tea.",
    "spun": "He spun in a fast circle.",
    "stake": "We drove a stake into the ground.",
    "state": "Texas is a big state.",
    "stet": "The teacher wrote stet to keep my word.",
    "stock": "The shop has a big stock of books.",
    "stride": "Take a long stride forward.",
    "stuck": "My boot got stuck in the mud.",
    "stun": "The bright flash can stun a fish.",
    "suck": "Try not to suck your thumb.",
    "swig": "He took a swig of cold water.",
    "swine": "Swine like to roll in the mud.",
    "tack": "I pinned the note with a tack.",
    "tame": "Our cat is gentle and tame.",
    "thick": "I spread thick jam on my toast.",
    "tick": "A tick crawled on the dog's ear.",
    "tide": "The tide came in over our toes.",
    "told": "She told me a secret.",
    "track": "The runner sped around the track.",
    "trick": "He showed me a card trick.",
    "trig": "The boat sat trig in the harbor.",
    "trot": "The horse began to trot.",
    "tuck": "Mom came in to tuck me in.",
    "twig": "A twig snapped under my foot.",
    "vine": "Grapes grow on a thick vine.",
    "whet": "The smell of food can whet your appetite.",
    "whine": "Please don't whine when you're tired.",
    "wide": "The river is very wide here.",
    "wine": "Grown-ups drank wine at dinner.",
}


def main() -> None:
    raw = WORDS_JSON.read_text(encoding="utf-8")
    data = json.loads(raw)

    weak_before = sum(1 for w in data if WEAK_RE.search(w.get("sentence", "")))
    replaced = 0
    unmatched_weak = []

    for entry in data:
        word = entry.get("word")
        if WEAK_RE.search(entry.get("sentence", "")):
            new_sentence = WORD_TO_NEW_SENTENCE.get(word)
            if new_sentence is None:
                # Generic fallback if we somehow miss one
                unmatched_weak.append(word)
                # Build a simple definition-style sentence
                new_sentence = f"I learned the spelling of {word} today."
            entry["sentence"] = new_sentence
            replaced += 1

    WORDS_JSON.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    weak_after = sum(1 for w in data if WEAK_RE.search(w.get("sentence", "")))
    print(f"weak before: {weak_before}")
    print(f"replaced:    {replaced}")
    print(f"weak after:  {weak_after}")
    if unmatched_weak:
        print(f"fallback used for {len(unmatched_weak)} words: {unmatched_weak}")


if __name__ == "__main__":
    main()
