// CountryQuiz — interactive per-country multiple-choice quiz.
//
// Sibling to StateQuiz (US version). Same three-mode shape:
//   'picker'  — checkboxes per category, "Start Quiz (N questions)" button
//   'quiz'    — one MC question at a time, green/red flash, auto-advance
//   'results' — score + missed questions + replay options
//
// Question generation
// -------------------
// For categorical single-string fields (capital, continent, region, language,
// currency, drivingSide, callingCode) wrong answers are sampled from REAL
// values on OTHER countries — kids learn by elimination.
//
// drivingSide is special: there are only two real values ("left" and "right"),
// so we hand-build 2 options instead of 4.
//
// For numerical fields (population, areaSqKm), other-country values cluster
// across enormous ranges (a few thousand to 1.4B), so plausible decoys are
// generated by multiplying/dividing the real value by 2-10x. That yields a
// distribution kids actually have to think about ("is Japan 1M or 100M?").
//
// For list fields (landmarks, physicalFeatures, funFacts) each item in the
// target's array becomes ONE "which of these is in <Country>?" question, with
// 3 decoys pulled from OTHER countries' arrays of the same kind. Capped so an
// all-checked quiz stays manageable.
//
// Missing fields degrade gracefully: countries with empty funFacts/landmarks/
// physicalFeatures simply produce zero questions in that category — and the
// picker row is hidden entirely (we filter count===0 out before render) so the
// kid never sees a useless checkbox.

'use client';

import { useCallback, useMemo, useState, useEffect, useRef } from 'react';
import Link from 'next/link';

// -------- Types (exported for the page wrapper) --------

export type CountryLandmark = {
  name: string;
  type?: string;
  description?: string;
  fact?: string;
};

export type CountryPhysicalFeature = {
  name: string;
  type?: string;
  description?: string;
  fact?: string;
};

export type CountryRecord = {
  iso2: string;
  iso3: string;
  name: string;
  capital: string;
  continent: string;
  region?: string;
  population?: number;
  populationYear?: number;
  areaSqKm?: number;
  languages?: string[];
  currency?: string;
  currencyCode?: string;
  drivingSide?: string;
  callingCode?: string;
  funFacts?: string[];
  landmarks?: CountryLandmark[];
  physicalFeatures?: CountryPhysicalFeature[];
};

// -------- Category registry --------

type CategoryId =
  | 'capital'
  | 'continent'
  | 'region'
  | 'population'
  | 'area'
  | 'language'
  | 'currency'
  | 'drivingSide'
  | 'callingCode'
  | 'funFacts'
  | 'landmarks'
  | 'physicalFeatures';

type CategoryDef = {
  id: CategoryId;
  label: string;
  // How many questions this category contributes for the GIVEN target country.
  // Zero means "not applicable" — the row is omitted entirely.
  count: number;
};

// Cap the per-list categories so all-checked stays manageable.
const MAX_LANDMARK_QS = 5;
const MAX_PHYSICAL_QS = 5;
const MAX_FUNFACT_QS = 3;

// -------- Question shape --------

type Question = {
  id: string;
  prompt: string;
  options: string[];
  correctIndex: number;
  // Plain-text explanation shown on incorrect answer.
  explanation: string;
  category: CategoryId;
};

// -------- Pure helpers --------

function shuffle<T>(arr: T[]): T[] {
  const copy = arr.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

// Pull up to `n` unique values from `pool` that aren't equal to any of
// `exclude`. Trim-compare so source data inconsistencies don't double up.
function pickDecoys(pool: string[], exclude: string[], n: number): string[] {
  const excludeSet = new Set(exclude.map((s) => s.trim()));
  const dedup: string[] = [];
  for (const v of shuffle(pool)) {
    const trimmed = v.trim();
    if (excludeSet.has(trimmed)) continue;
    if (dedup.includes(trimmed)) continue;
    dedup.push(trimmed);
    if (dedup.length >= n) break;
  }
  return dedup;
}

// Build the 4-option array from a correct answer + decoy pool, then shuffle.
// If the decoy pool is too thin (rare — only happens if every other country
// shares the same value), we backfill with "(none)" so we still have 4 options.
function buildOptions(correct: string, decoyPool: string[]): {
  options: string[];
  correctIndex: number;
} {
  const decoys = pickDecoys(decoyPool, [correct], 3);
  while (decoys.length < 3) decoys.push('(none)');
  const all = shuffle([correct, ...decoys]);
  return { options: all, correctIndex: all.indexOf(correct) };
}

// Format population with thousands separators, no decimals. Used both as the
// "correct" answer string and for decoy generation so the picker matches.
function formatPop(n: number): string {
  return n.toLocaleString('en-US');
}

// Format area in km² with thousands separators.
function formatArea(n: number): string {
  return `${n.toLocaleString('en-US')} km²`;
}

// Generate 3 numerical decoys by scaling the real value up/down. Picks 3
// random factors from a candidate set so the decoys span order-of-magnitude
// space (kid can't just pick the smallest/largest). We round to keep them
// looking like real population/area figures.
function generateNumericDecoys(real: number, formatter: (n: number) => string): string[] {
  // Factors include sub-1 (smaller) and >1 (larger) so the real value isn't
  // obviously the middle of the pack.
  const factors = [0.1, 0.2, 0.33, 0.5, 2, 3, 5, 10];
  const picks = shuffle(factors).slice(0, 3);
  return picks
    .map((f) => Math.max(1, Math.round(real * f)))
    .map(formatter);
}

// -------- Question generators --------

function generateQuestions(
  target: CountryRecord,
  others: CountryRecord[],
  enabled: Set<CategoryId>,
): Question[] {
  const out: Question[] = [];

  // Simple single-string field questions. Reads the field via a getter so we
  // can support both direct keys and computed/optional fields cleanly.
  const simpleField = (
    id: CategoryId,
    label: string,
    getter: (c: CountryRecord) => string | null | undefined,
    prompt: string,
    explainTpl?: (val: string) => string,
  ) => {
    if (!enabled.has(id)) return;
    const correct = getter(target);
    if (typeof correct !== 'string' || !correct) return;
    const pool = others
      .map(getter)
      .filter((v): v is string => typeof v === 'string' && v.length > 0);
    const { options, correctIndex } = buildOptions(correct, pool);
    out.push({
      id: `${id}-${target.iso2}`,
      prompt,
      options,
      correctIndex,
      explanation: explainTpl
        ? explainTpl(correct)
        : `${target.name}'s ${label} is ${correct}.`,
      category: id,
    });
  };

  simpleField('capital', 'capital', (c) => c.capital, `What's the capital of ${target.name}?`);
  simpleField('continent', 'continent', (c) => c.continent, `Which continent is ${target.name} on?`);
  simpleField('region', 'region', (c) => c.region, `Which region is ${target.name} in?`);
  simpleField(
    'currency',
    'currency',
    (c) => c.currency,
    `What currency does ${target.name} use?`,
  );
  simpleField(
    'callingCode',
    'calling code',
    (c) => c.callingCode,
    `What's ${target.name}'s international calling code?`,
  );

  // Language: pick the FIRST language for the prompt's correct answer, decoys
  // from other countries' first languages. (Multi-language countries: we still
  // ask one question — picking randomly across the array would let "official
  // language of X" overlap with neighbours too often.)
  if (enabled.has('language')) {
    const langs = target.languages ?? [];
    if (langs.length > 0) {
      const correct = langs[0];
      const pool = others.flatMap((c) => c.languages ?? []);
      // Exclude every language the target speaks from the decoy pool so we
      // don't accidentally label a real co-official language as wrong.
      const filteredPool = pool.filter((l) => !langs.includes(l));
      const { options, correctIndex } = buildOptions(correct, filteredPool);
      out.push({
        id: `language-${target.iso2}`,
        prompt: `Which of these languages is spoken in ${target.name}?`,
        options,
        correctIndex,
        explanation:
          langs.length > 1
            ? `Languages of ${target.name}: ${langs.join(', ')}.`
            : `The main language of ${target.name} is ${correct}.`,
        category: 'language',
      });
    }
  }

  // Driving side: only TWO real values (left/right). We hand-build 2 options
  // instead of going through buildOptions so the kid doesn't see "(none)" fill.
  if (enabled.has('drivingSide') && typeof target.drivingSide === 'string' && target.drivingSide) {
    const correct = target.drivingSide;
    const options = shuffle(['left', 'right']);
    out.push({
      id: `drivingSide-${target.iso2}`,
      prompt: `Which side of the road do they drive on in ${target.name}?`,
      options,
      correctIndex: options.indexOf(correct),
      explanation: `${target.name} drives on the ${correct}.`,
      category: 'drivingSide',
    });
  }

  // Population: 3 plausible decoys via multiply/divide. Other-country
  // populations span orders of magnitude (~1k to 1.4B) so sampling from them
  // makes the real answer too obvious — engineered decoys are tighter.
  if (enabled.has('population') && typeof target.population === 'number') {
    const real = target.population;
    const decoys = generateNumericDecoys(real, formatPop);
    const { options, correctIndex } = buildOptions(formatPop(real), decoys);
    const yearSuffix = target.populationYear ? ` (${target.populationYear})` : '';
    out.push({
      id: `population-${target.iso2}`,
      prompt: `About how many people live in ${target.name}?`,
      options,
      correctIndex,
      explanation: `${target.name}'s population is about ${formatPop(real)}${yearSuffix}.`,
      category: 'population',
    });
  }

  // Area: same approach as population — multiply/divide decoys.
  if (enabled.has('area') && typeof target.areaSqKm === 'number') {
    const real = target.areaSqKm;
    const decoys = generateNumericDecoys(real, formatArea);
    const { options, correctIndex } = buildOptions(formatArea(real), decoys);
    out.push({
      id: `area-${target.iso2}`,
      prompt: `About how big is ${target.name}?`,
      options,
      correctIndex,
      explanation: `${target.name} covers about ${formatArea(real)}.`,
      category: 'area',
    });
  }

  // Fun facts: each fact is the right answer; decoys = other countries' fun
  // facts. With the current dataset funFacts is empty everywhere, but we keep
  // the generator wired so when content lands it Just Works.
  if (enabled.has('funFacts') && Array.isArray(target.funFacts) && target.funFacts.length > 0) {
    const facts = shuffle(target.funFacts).slice(0, MAX_FUNFACT_QS);
    const decoyPool = others.flatMap((c) => c.funFacts ?? []);
    for (let i = 0; i < facts.length; i++) {
      const fact = facts[i];
      const { options, correctIndex } = buildOptions(fact, decoyPool);
      out.push({
        id: `funFact-${target.iso2}-${i}`,
        prompt: `Which of these is true about ${target.name}?`,
        options,
        correctIndex,
        explanation: `True about ${target.name}: ${fact}`,
        category: 'funFacts',
      });
    }
  }

  // Landmarks: each landmark is the right answer; decoys = other countries'
  // landmark names. We display just the NAME in options (descriptions get long).
  if (enabled.has('landmarks') && Array.isArray(target.landmarks) && target.landmarks.length > 0) {
    const landmarks = shuffle(target.landmarks).slice(0, MAX_LANDMARK_QS);
    const decoyPool = others.flatMap((c) =>
      Array.isArray(c.landmarks) ? c.landmarks.map((l) => l.name) : [],
    );
    for (let i = 0; i < landmarks.length; i++) {
      const lm = landmarks[i];
      const { options, correctIndex } = buildOptions(lm.name, decoyPool);
      const tail = lm.description ? ` ${lm.description}` : '';
      out.push({
        id: `landmark-${target.iso2}-${i}`,
        prompt: `Which landmark is in ${target.name}?`,
        options,
        correctIndex,
        explanation: `${lm.name} is in ${target.name}.${tail}`,
        category: 'landmarks',
      });
    }
  }

  // Physical features: same shape as landmarks.
  if (
    enabled.has('physicalFeatures') &&
    Array.isArray(target.physicalFeatures) &&
    target.physicalFeatures.length > 0
  ) {
    const features = shuffle(target.physicalFeatures).slice(0, MAX_PHYSICAL_QS);
    const decoyPool = others.flatMap((c) =>
      Array.isArray(c.physicalFeatures) ? c.physicalFeatures.map((f) => f.name) : [],
    );
    for (let i = 0; i < features.length; i++) {
      const f = features[i];
      const { options, correctIndex } = buildOptions(f.name, decoyPool);
      const tail = f.description ? ` ${f.description}` : '';
      out.push({
        id: `phys-${target.iso2}-${i}`,
        prompt: `Which natural feature is in ${target.name}?`,
        options,
        correctIndex,
        explanation: `${f.name} is in ${target.name}.${tail}`,
        category: 'physicalFeatures',
      });
    }
  }

  return shuffle(out);
}

// Count what a fully-checked quiz would produce for THIS country, used to
// drive picker row labels and to hide rows with zero applicable questions.
function countForCategory(id: CategoryId, target: CountryRecord): number {
  switch (id) {
    case 'capital':
      return target.capital ? 1 : 0;
    case 'continent':
      return target.continent ? 1 : 0;
    case 'region':
      return target.region ? 1 : 0;
    case 'population':
      return typeof target.population === 'number' ? 1 : 0;
    case 'area':
      return typeof target.areaSqKm === 'number' ? 1 : 0;
    case 'language':
      return Array.isArray(target.languages) && target.languages.length > 0 ? 1 : 0;
    case 'currency':
      return target.currency ? 1 : 0;
    case 'drivingSide':
      return target.drivingSide ? 1 : 0;
    case 'callingCode':
      return target.callingCode ? 1 : 0;
    case 'funFacts':
      return Array.isArray(target.funFacts)
        ? Math.min(target.funFacts.length, MAX_FUNFACT_QS)
        : 0;
    case 'landmarks':
      return Array.isArray(target.landmarks)
        ? Math.min(target.landmarks.length, MAX_LANDMARK_QS)
        : 0;
    case 'physicalFeatures':
      return Array.isArray(target.physicalFeatures)
        ? Math.min(target.physicalFeatures.length, MAX_PHYSICAL_QS)
        : 0;
  }
}

const CATEGORY_LABELS: Record<CategoryId, string> = {
  capital: 'Capital city',
  continent: 'Continent',
  region: 'Region',
  population: 'Population',
  area: 'Area',
  language: 'Language',
  currency: 'Currency',
  drivingSide: 'Driving side',
  callingCode: 'Calling code',
  funFacts: 'Fun facts',
  landmarks: 'Famous landmarks',
  physicalFeatures: 'Physical features',
};

// Display order in the picker.
const CATEGORY_ORDER: CategoryId[] = [
  'capital',
  'continent',
  'region',
  'population',
  'area',
  'language',
  'currency',
  'drivingSide',
  'callingCode',
  'landmarks',
  'physicalFeatures',
  'funFacts',
];

// -------- Timing --------

const FEEDBACK_DELAY_MS = 1500; // both right and wrong — kid sees the result

// -------- Component --------

type Mode = 'picker' | 'quiz' | 'results';

type Props = {
  country: CountryRecord;
  others: CountryRecord[];
};

export default function CountryQuiz({ country, others }: Props) {
  // Build the per-country category list once. Categories with count 0 (e.g.
  // funFacts on a country with an empty array) are filtered out entirely.
  const categories: CategoryDef[] = useMemo(() => {
    return CATEGORY_ORDER
      .map((id) => ({ id, label: CATEGORY_LABELS[id], count: countForCategory(id, country) }))
      .filter((c) => c.count > 0);
  }, [country]);

  const [mode, setMode] = useState<Mode>('picker');
  const [enabled, setEnabled] = useState<Set<CategoryId>>(
    () => new Set(categories.map((c) => c.id)),
  );

  const totalQuestions = useMemo(
    () => categories.filter((c) => enabled.has(c.id)).reduce((sum, c) => sum + c.count, 0),
    [categories, enabled],
  );

  // Question queue + cursor — only relevant in 'quiz' and 'results' modes.
  const [queue, setQueue] = useState<Question[]>([]);
  const [index, setIndex] = useState(0);
  const [score, setScore] = useState(0);
  // scoreRef mirrors `score` synchronously so the advance timer can read the
  // up-to-date score without React batching surprises (parallel to StateQuiz).
  const scoreRef = useRef(0);
  const [misses, setMisses] = useState<Array<{ q: Question; pickedIndex: number }>>([]);
  const [feedback, setFeedback] = useState<null | { kind: 'right' | 'wrong'; pickedIndex: number }>(
    null,
  );

  // Single advance timer; cleared on unmount or before scheduling another.
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    return () => {
      if (timerRef.current !== null) clearTimeout(timerRef.current);
    };
  }, []);

  const toggleCategory = useCallback((id: CategoryId) => {
    setEnabled((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }, []);

  const selectAll = useCallback(() => {
    setEnabled(new Set(categories.map((c) => c.id)));
  }, [categories]);

  const clearAll = useCallback(() => {
    setEnabled(new Set());
  }, []);

  const startQuiz = useCallback(() => {
    const qs = generateQuestions(country, others, enabled);
    if (qs.length === 0) return;
    setQueue(qs);
    setIndex(0);
    setScore(0);
    scoreRef.current = 0;
    setMisses([]);
    setFeedback(null);
    setMode('quiz');
  }, [country, others, enabled]);

  const playAgainSame = useCallback(() => {
    // Re-generate so options re-shuffle and the capped list categories pick
    // a fresh random subset — replays feel new.
    startQuiz();
  }, [startQuiz]);

  const backToPicker = useCallback(() => {
    if (timerRef.current !== null) clearTimeout(timerRef.current);
    setFeedback(null);
    setMode('picker');
  }, []);

  const handleAnswer = useCallback(
    (pickedIndex: number) => {
      if (feedback !== null) return; // ignore during 1.5s flash
      const current = queue[index];
      if (!current) return;
      const isRight = pickedIndex === current.correctIndex;
      setFeedback({ kind: isRight ? 'right' : 'wrong', pickedIndex });
      if (isRight) {
        scoreRef.current += 1;
        setScore(scoreRef.current);
      } else {
        setMisses((m) => [...m, { q: current, pickedIndex }]);
      }
      if (timerRef.current !== null) clearTimeout(timerRef.current);
      timerRef.current = setTimeout(() => {
        timerRef.current = null;
        setFeedback(null);
        if (index + 1 >= queue.length) {
          setMode('results');
        } else {
          setIndex((i) => i + 1);
        }
      }, FEEDBACK_DELAY_MS);
    },
    [feedback, queue, index],
  );

  // ---------------- Picker ----------------
  if (mode === 'picker') {
    return (
      <div className="min-h-screen bg-gradient-to-b from-sky-50 via-indigo-50 to-white py-8 sm:py-12 px-4">
        <div className="max-w-2xl mx-auto">
          <Link
            href={`/geography/world/country/${country.iso2.toLowerCase()}`}
            className="inline-flex items-center gap-1 text-sm font-semibold text-sky-700 hover:text-sky-500 transition-colors mb-4"
          >
            ← Back to {country.name}
          </Link>

          <header className="bg-gradient-to-br from-sky-600 to-indigo-600 text-white rounded-2xl shadow-md p-6 sm:p-8 mb-6">
            <h1 className="text-3xl sm:text-4xl font-black mb-1">Quiz: {country.name}</h1>
            <p className="text-sky-50 text-base sm:text-lg">
              Pick what to quiz on, then start.
            </p>
          </header>

          <section className="bg-white rounded-2xl border border-sky-100 shadow-sm p-5 sm:p-6 mb-6">
            <div className="flex items-center justify-between gap-2 mb-4">
              <h2 className="text-lg sm:text-xl font-black text-sky-900">Categories</h2>
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={selectAll}
                  className="text-xs sm:text-sm font-semibold text-sky-700 hover:text-sky-500 px-2 py-1 rounded"
                >
                  Select all
                </button>
                <button
                  type="button"
                  onClick={clearAll}
                  className="text-xs sm:text-sm font-semibold text-gray-600 hover:text-gray-400 px-2 py-1 rounded"
                >
                  Clear all
                </button>
              </div>
            </div>

            <ul className="space-y-1">
              {categories.map((c) => {
                const checked = enabled.has(c.id);
                return (
                  <li key={c.id}>
                    <label className="flex items-center gap-3 py-2 px-3 rounded-xl hover:bg-sky-50 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() => toggleCategory(c.id)}
                        className="h-5 w-5 accent-sky-600 cursor-pointer"
                      />
                      <span className="flex-1 text-base sm:text-lg font-semibold text-gray-800">
                        {c.label}
                      </span>
                      <span className="text-xs sm:text-sm text-sky-700 font-bold tabular-nums">
                        +{c.count}
                      </span>
                    </label>
                  </li>
                );
              })}
            </ul>
          </section>

          <button
            type="button"
            onClick={startQuiz}
            disabled={totalQuestions === 0}
            className="w-full bg-gradient-to-br from-sky-600 to-indigo-600 hover:from-sky-500 hover:to-indigo-500 disabled:from-gray-300 disabled:to-gray-300 disabled:cursor-not-allowed text-white font-black text-xl sm:text-2xl py-5 rounded-2xl shadow-md transition-all"
          >
            {totalQuestions === 0
              ? 'Pick at least one category'
              : `Start Quiz (${totalQuestions} question${totalQuestions === 1 ? '' : 's'})`}
          </button>
        </div>
      </div>
    );
  }

  // ---------------- In-Quiz ----------------
  if (mode === 'quiz') {
    const current = queue[index];
    if (!current) {
      // Shouldn't happen — startQuiz guards an empty queue, and the advance
      // timer transitions to 'results' before we'd index past the end.
      return null;
    }
    const pct = ((index + (feedback ? 1 : 0)) / queue.length) * 100;
    const letterFor = (i: number) => 'ABCD'[i];

    return (
      <div className="min-h-screen bg-gradient-to-b from-sky-50 via-indigo-50 to-white py-6 sm:py-10 px-4">
        <div className="max-w-2xl mx-auto">
          {/* Top bar */}
          <div className="flex items-center justify-between gap-2 mb-3 text-sm sm:text-base">
            <button
              type="button"
              onClick={backToPicker}
              className="font-semibold text-sky-700 hover:text-sky-500 transition-colors"
            >
              ← Back to picker
            </button>
            <div className="font-bold text-gray-700 tabular-nums">
              Question {index + 1} of {queue.length} · Score: {score}
            </div>
          </div>

          {/* Progress bar */}
          <div className="w-full h-2 bg-sky-100 rounded-full overflow-hidden mb-6">
            <div
              className="h-full bg-gradient-to-r from-sky-500 to-indigo-500 transition-all duration-300"
              style={{ width: `${pct}%` }}
            />
          </div>

          {/* Question */}
          <div className="bg-white rounded-2xl border border-sky-100 shadow-sm p-5 sm:p-7 mb-5">
            <h2 className="text-xl sm:text-2xl font-black text-sky-900 leading-snug">
              {current.prompt}
            </h2>
          </div>

          {/* Options */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {current.options.map((opt, i) => {
              const isCorrect = i === current.correctIndex;
              const isPicked = feedback?.pickedIndex === i;
              let stateClass =
                'bg-white border-sky-200 hover:border-sky-400 hover:bg-sky-50 text-gray-800';
              if (feedback) {
                if (isPicked && feedback.kind === 'right') {
                  stateClass = 'bg-sky-500 border-sky-600 text-white';
                } else if (isPicked && feedback.kind === 'wrong') {
                  stateClass = 'bg-red-500 border-red-600 text-white';
                } else if (isCorrect) {
                  stateClass = 'bg-sky-500 border-sky-600 text-white';
                } else {
                  stateClass = 'bg-white border-gray-200 text-gray-400';
                }
              }
              return (
                <button
                  key={i}
                  type="button"
                  onClick={() => handleAnswer(i)}
                  disabled={feedback !== null}
                  className={`text-left p-4 rounded-2xl border-2 font-semibold text-base sm:text-lg shadow-sm transition-all ${stateClass}`}
                >
                  <span className="inline-block w-7 h-7 rounded-full bg-black/10 text-center leading-7 font-black mr-3 text-sm">
                    {letterFor(i)}
                  </span>
                  {opt}
                </button>
              );
            })}
          </div>

          {/* Feedback text under the options */}
          {feedback && (
            <div
              className={`mt-5 p-4 rounded-2xl text-base sm:text-lg font-semibold ${
                feedback.kind === 'right'
                  ? 'bg-sky-100 text-sky-900'
                  : 'bg-red-100 text-red-900'
              }`}
            >
              {feedback.kind === 'right' ? 'Correct! ' : 'Not quite. '}
              {current.explanation}
            </div>
          )}
        </div>
      </div>
    );
  }

  // ---------------- Results ----------------
  // mode === 'results'
  return (
    <div className="min-h-screen bg-gradient-to-b from-sky-50 via-indigo-50 to-white py-8 sm:py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <header className="bg-gradient-to-br from-sky-600 to-indigo-600 text-white rounded-2xl shadow-md p-6 sm:p-8 mb-6 text-center">
          <h1 className="text-3xl sm:text-4xl font-black mb-2">All done!</h1>
          <p className="text-2xl sm:text-3xl font-black">
            You got {score} of {queue.length}!
          </p>
        </header>

        {misses.length > 0 && (
          <section className="bg-white rounded-2xl border border-sky-100 shadow-sm p-5 sm:p-6 mb-6">
            <h2 className="text-lg sm:text-xl font-black text-sky-900 mb-3">
              Worth another look ({misses.length})
            </h2>
            <ul className="space-y-3">
              {misses.map(({ q }, idx) => (
                <li key={idx} className="border-l-4 border-sky-400 pl-3">
                  <p className="font-semibold text-gray-800">{q.prompt}</p>
                  <p className="text-sm text-sky-700 font-medium">
                    Correct: {q.options[q.correctIndex]}
                  </p>
                  <p className="text-sm text-gray-600 italic mt-1">{q.explanation}</p>
                </li>
              ))}
            </ul>
          </section>
        )}

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <button
            type="button"
            onClick={playAgainSame}
            className="bg-gradient-to-br from-sky-600 to-indigo-600 hover:from-sky-500 hover:to-indigo-500 text-white font-black text-base sm:text-lg py-4 rounded-2xl shadow-md transition-all"
          >
            Play Again
          </button>
          <button
            type="button"
            onClick={backToPicker}
            className="bg-white border-2 border-sky-400 text-sky-700 hover:bg-sky-50 font-black text-base sm:text-lg py-4 rounded-2xl shadow-sm transition-all"
          >
            Pick Different Categories
          </button>
        </div>

        <div className="mt-6 text-center">
          <Link
            href={`/geography/world/country/${country.iso2.toLowerCase()}`}
            className="inline-flex items-center gap-1 text-sm font-semibold text-sky-700 hover:text-sky-500"
          >
            ← Back to {country.name}
          </Link>
        </div>
      </div>
    </div>
  );
}
