"""Expand parks arrays in states.json to 12-15 entries per state.

Reads existing parks (most states have 5), appends curated additions,
dedupes by name (case-insensitive), caps each state at 15.
Preserves every other field on the state object.
"""

import json
from pathlib import Path

STATES_PATH = Path("C:/Users/dglazier/source/Personal/mammas-place/data/states.json")
MAX_PARKS = 15

# Each entry: list of new parks to merge with existing. Dedupe is by name (case-insensitive).
ADDITIONS = {
    "AL": [
        {"name": "Russell Cave National Monument", "type": "monument", "description": "An ancient cave shelter used by people for over 10,000 years.", "yearEstablished": 1961},
        {"name": "Little River Canyon National Preserve", "type": "preserve", "description": "One of the deepest canyons east of the Mississippi.", "yearEstablished": 1992},
        {"name": "Tuskegee Airmen National Historic Site", "type": "historic", "description": "Honors the first African American military pilots.", "yearEstablished": 1998},
        {"name": "Gulf State Park", "type": "state", "description": "Beautiful white sand beaches and a fishing pier on the Gulf Coast.", "yearEstablished": 1939},
        {"name": "Oak Mountain State Park", "type": "state", "description": "Alabama's largest state park with hiking, fishing, and a raptor center.", "yearEstablished": 1927},
        {"name": "Cheaha State Park", "type": "state", "description": "Sits atop Alabama's highest mountain with sweeping views.", "yearEstablished": 1933},
        {"name": "DeSoto State Park", "type": "state", "description": "Waterfalls and wildflowers atop Lookout Mountain.", "yearEstablished": 1939},
        {"name": "Lake Guntersville State Park", "type": "state", "description": "Tennessee River lake park famous for bald eagle sightings.", "yearEstablished": 1947},
        {"name": "Joe Wheeler State Park", "type": "state", "description": "Lakeside park with fishing, boating, and a marina.", "yearEstablished": None},
        {"name": "Wind Creek State Park", "type": "state", "description": "Popular camping park on Lake Martin.", "yearEstablished": None},
    ],
    "AK": [
        {"name": "Wrangell-St. Elias National Park", "type": "national", "description": "The largest national park in the U.S., bigger than Switzerland.", "yearEstablished": 1980},
        {"name": "Glacier Bay National Park", "type": "national", "description": "Tidewater glaciers calving into icy blue waters.", "yearEstablished": 1980},
        {"name": "Katmai National Park", "type": "national", "description": "Famous for brown bears catching salmon at Brooks Falls.", "yearEstablished": 1980},
        {"name": "Lake Clark National Park", "type": "national", "description": "Volcanoes, glaciers, and salmon-filled lakes.", "yearEstablished": 1980},
        {"name": "Kobuk Valley National Park", "type": "national", "description": "Remote park with giant sand dunes above the Arctic Circle.", "yearEstablished": 1980},
        {"name": "Gates of the Arctic National Park", "type": "national", "description": "A vast wilderness with no roads or trails.", "yearEstablished": 1980},
        {"name": "Chugach State Park", "type": "state", "description": "Half-million-acre park right next to Anchorage.", "yearEstablished": 1970},
        {"name": "Denali State Park", "type": "state", "description": "Stunning views of Denali, North America's tallest peak.", "yearEstablished": 1970},
        {"name": "Kachemak Bay State Park", "type": "state", "description": "Alaska's first state park with glaciers and ocean coves.", "yearEstablished": 1970},
    ],
    "AZ": [
        {"name": "Petrified Forest National Park", "type": "national", "description": "Colorful fossilized logs from a 200-million-year-old forest.", "yearEstablished": 1962},
        {"name": "Saguaro National Park", "type": "national", "description": "Protects giant saguaro cacti that grow up to 50 feet tall.", "yearEstablished": 1994},
        {"name": "Monument Valley", "type": "state", "description": "Iconic red sandstone buttes on Navajo tribal land.", "yearEstablished": None},
        {"name": "Canyon de Chelly National Monument", "type": "monument", "description": "Ancient cliff dwellings in red rock canyons.", "yearEstablished": 1931},
        {"name": "Wupatki National Monument", "type": "monument", "description": "Red sandstone pueblo ruins from ancient Sinagua people.", "yearEstablished": 1924},
        {"name": "Sunset Crater Volcano National Monument", "type": "monument", "description": "A 1,000-year-old volcanic cinder cone.", "yearEstablished": 1930},
        {"name": "Chiricahua National Monument", "type": "monument", "description": "A 'wonderland of rocks' with balanced stone spires.", "yearEstablished": 1924},
        {"name": "Slide Rock State Park", "type": "state", "description": "A natural water slide through Oak Creek Canyon's red rocks.", "yearEstablished": 1985},
        {"name": "Lost Dutchman State Park", "type": "state", "description": "Named for a legendary lost gold mine in the Superstition Mountains.", "yearEstablished": 1977},
        {"name": "Kartchner Caverns State Park", "type": "state", "description": "A 'living' limestone cave with growing formations.", "yearEstablished": 1988},
    ],
    "AR": [
        {"name": "Buffalo National River", "type": "national", "description": "The first national river in the U.S., great for floating.", "yearEstablished": 1972},
        {"name": "Pea Ridge National Military Park", "type": "historic", "description": "Site of a major Civil War battle in the West.", "yearEstablished": 1956},
        {"name": "Petit Jean State Park", "type": "state", "description": "Arkansas's first state park with waterfalls and a famous overlook.", "yearEstablished": 1923},
        {"name": "Devil's Den State Park", "type": "state", "description": "Caves, crevices, and a beautiful CCC-built lake.", "yearEstablished": 1933},
        {"name": "Mount Magazine State Park", "type": "state", "description": "Sits on Arkansas's highest mountain with stunning views.", "yearEstablished": 2002},
        {"name": "Crater of Diamonds State Park", "type": "state", "description": "The only place where you can hunt for real diamonds and keep them.", "yearEstablished": 1972},
        {"name": "Lake Ouachita State Park", "type": "state", "description": "Crystal-clear lake great for swimming and fishing.", "yearEstablished": 1955},
        {"name": "Mammoth Spring State Park", "type": "state", "description": "One of the world's largest springs, flowing 9 million gallons an hour.", "yearEstablished": 1957},
        {"name": "Queen Wilhelmina State Park", "type": "state", "description": "Mountain park with a lodge atop Rich Mountain.", "yearEstablished": None},
        {"name": "Cossatot River State Park", "type": "state", "description": "Wild whitewater river through the Ouachita Mountains.", "yearEstablished": 1988},
    ],
    "CA": [
        {"name": "Sequoia National Park", "type": "national", "description": "Home to the world's largest tree by volume, General Sherman.", "yearEstablished": 1890},
        {"name": "Kings Canyon National Park", "type": "national", "description": "Deep canyons and groves of giant sequoia trees.", "yearEstablished": 1940},
        {"name": "Lassen Volcanic National Park", "type": "national", "description": "Steaming fumaroles, mud pots, and a volcanic peak.", "yearEstablished": 1916},
        {"name": "Channel Islands National Park", "type": "national", "description": "Five islands often called the 'Galapagos of North America'.", "yearEstablished": 1980},
        {"name": "Pinnacles National Park", "type": "national", "description": "Ancient volcanic rock spires and home to endangered California condors.", "yearEstablished": 2013},
        {"name": "Death Valley National Park", "type": "national", "description": "The hottest and lowest place in North America.", "yearEstablished": 1994},
        {"name": "Point Reyes National Seashore", "type": "seashore", "description": "Wild Pacific coastline with elephant seals and a historic lighthouse.", "yearEstablished": 1962},
        {"name": "Muir Woods National Monument", "type": "monument", "description": "Ancient coast redwoods just north of San Francisco.", "yearEstablished": 1908},
    ],
    "CO": [
        {"name": "Rocky Mountain National Park", "type": "national", "description": "Soaring peaks, alpine lakes, and the highest paved road in the U.S.", "yearEstablished": 1915},
        {"name": "Mesa Verde National Park", "type": "national", "description": "Ancient cliff dwellings built by the Ancestral Puebloans.", "yearEstablished": 1906},
        {"name": "Great Sand Dunes National Park", "type": "national", "description": "The tallest sand dunes in North America at the foot of the Rockies.", "yearEstablished": 2004},
        {"name": "Black Canyon of the Gunnison National Park", "type": "national", "description": "A narrow, deep canyon with sheer cliffs.", "yearEstablished": 1999},
        {"name": "Dinosaur National Monument", "type": "monument", "description": "Famous quarry wall studded with real dinosaur bones.", "yearEstablished": 1915},
        {"name": "Colorado National Monument", "type": "monument", "description": "Red rock canyons and towering monoliths.", "yearEstablished": 1911},
        {"name": "Florissant Fossil Beds National Monument", "type": "monument", "description": "Ancient petrified redwood stumps and fossil insects.", "yearEstablished": 1969},
        {"name": "Eldorado Canyon State Park", "type": "state", "description": "Famous rock-climbing canyon with sandstone cliffs.", "yearEstablished": 1978},
        {"name": "Roxborough State Park", "type": "state", "description": "Dramatic red rock formations south of Denver.", "yearEstablished": 1975},
    ],
    "CT": [
        {"name": "Weir Farm National Historical Park", "type": "historic", "description": "The home and studio of famous American Impressionist painter J. Alden Weir.", "yearEstablished": 1990},
        {"name": "Hammonasset Beach State Park", "type": "state", "description": "Connecticut's longest public beach on Long Island Sound.", "yearEstablished": 1920},
        {"name": "Sleeping Giant State Park", "type": "state", "description": "A mountain shaped like a sleeping man, with great hiking trails.", "yearEstablished": 1924},
        {"name": "Talcott Mountain State Park", "type": "state", "description": "Heublein Tower offers views of four states.", "yearEstablished": 1965},
        {"name": "Kent Falls State Park", "type": "state", "description": "Series of waterfalls cascading down 250 feet.", "yearEstablished": 1919},
        {"name": "Devil's Hopyard State Park", "type": "state", "description": "Chapman Falls and unusual rock potholes.", "yearEstablished": 1919},
        {"name": "Gillette Castle State Park", "type": "state", "description": "A stone castle built by an actor who played Sherlock Holmes.", "yearEstablished": 1943},
        {"name": "Macedonia Brook State Park", "type": "state", "description": "Mountain views and hiking in the northwest hills.", "yearEstablished": None},
        {"name": "Rocky Neck State Park", "type": "state", "description": "Sandy beach and salt marsh on Long Island Sound.", "yearEstablished": 1931},
    ],
    "DE": [
        {"name": "First State National Historical Park", "type": "historic", "description": "Tells the story of Delaware, the first state to ratify the Constitution.", "yearEstablished": 2013},
        {"name": "Cape Henlopen State Park", "type": "state", "description": "Sand dunes and beaches where the Delaware Bay meets the Atlantic.", "yearEstablished": 1964},
        {"name": "Delaware Seashore State Park", "type": "state", "description": "Six miles of ocean beach perfect for swimming and surfing.", "yearEstablished": 1965},
        {"name": "Bombay Hook National Wildlife Refuge", "type": "preserve", "description": "Important stopover for migrating snow geese and shorebirds.", "yearEstablished": 1937},
        {"name": "Brandywine Creek State Park", "type": "state", "description": "Historic stone walls and rolling meadows along the Brandywine.", "yearEstablished": 1965},
        {"name": "White Clay Creek State Park", "type": "state", "description": "Forests and streams great for hiking and biking.", "yearEstablished": 1968},
        {"name": "Trap Pond State Park", "type": "state", "description": "Home to the northernmost natural bald cypress swamp.", "yearEstablished": 1951},
    ],
    "DC": [
        {"name": "Rock Creek Park", "type": "national", "description": "A huge forested park right in the middle of Washington, D.C.", "yearEstablished": 1890},
        {"name": "Constitution Gardens", "type": "national", "description": "A peaceful lake and memorial honoring the signers of the Declaration of Independence.", "yearEstablished": 1976},
        {"name": "Theodore Roosevelt Island", "type": "national", "description": "A wooded island memorial to America's conservationist president.", "yearEstablished": 1932},
        {"name": "Anacostia Park", "type": "national", "description": "Riverside park with sports fields and a roller-skating pavilion.", "yearEstablished": 1918},
    ],
    "FL": [
        {"name": "Biscayne National Park", "type": "national", "description": "A mostly-underwater park protecting coral reefs and shipwrecks.", "yearEstablished": 1980},
        {"name": "Canaveral National Seashore", "type": "seashore", "description": "Wild, undeveloped beaches near the Kennedy Space Center.", "yearEstablished": 1975},
        {"name": "Castillo de San Marcos National Monument", "type": "monument", "description": "A 300-year-old Spanish stone fort in St. Augustine.", "yearEstablished": 1924},
        {"name": "Big Cypress National Preserve", "type": "preserve", "description": "Swampy wilderness next to the Everglades, home to Florida panthers.", "yearEstablished": 1974},
        {"name": "Wekiwa Springs State Park", "type": "state", "description": "Crystal-clear spring perfect for swimming and canoeing.", "yearEstablished": 1969},
        {"name": "Bahia Honda State Park", "type": "state", "description": "One of the most beautiful beaches in the Florida Keys.", "yearEstablished": 1961},
        {"name": "Anastasia State Park", "type": "state", "description": "Four miles of beach and ancient sand dunes.", "yearEstablished": 1949},
        {"name": "Myakka River State Park", "type": "state", "description": "One of Florida's oldest state parks with alligators and bird watching.", "yearEstablished": 1934},
        {"name": "Ichetucknee Springs State Park", "type": "state", "description": "Famous for tubing down a crystal-clear spring-fed river.", "yearEstablished": 1970},
        {"name": "Honeymoon Island State Park", "type": "state", "description": "Florida's most popular state park with sandy beaches and ospreys.", "yearEstablished": 1974},
    ],
    "GA": [
        {"name": "Cumberland Island National Seashore", "type": "seashore", "description": "A wild barrier island with beaches and free-roaming horses.", "yearEstablished": 1972},
        {"name": "Chattahoochee River National Recreation Area", "type": "national", "description": "River park stretching through metro Atlanta.", "yearEstablished": 1978},
        {"name": "Fort Pulaski National Monument", "type": "monument", "description": "A massive brick fort guarding the Savannah River.", "yearEstablished": 1924},
        {"name": "Ocmulgee Mounds National Historical Park", "type": "historic", "description": "Ancient earthwork mounds built by Native Americans.", "yearEstablished": 1936},
        {"name": "Andersonville National Historic Site", "type": "historic", "description": "A solemn site that was a Confederate prison camp.", "yearEstablished": 1970},
        {"name": "Providence Canyon State Park", "type": "state", "description": "Georgia's 'Little Grand Canyon' carved by erosion.", "yearEstablished": 1971},
        {"name": "Cloudland Canyon State Park", "type": "state", "description": "Deep canyon and waterfalls atop Lookout Mountain.", "yearEstablished": 1938},
        {"name": "Amicalola Falls State Park", "type": "state", "description": "Home to one of the tallest waterfalls in the eastern U.S.", "yearEstablished": 1940},
        {"name": "Tallulah Gorge State Park", "type": "state", "description": "A two-mile-long, 1,000-foot-deep gorge.", "yearEstablished": 1993},
        {"name": "Stone Mountain Park", "type": "state", "description": "A giant granite dome with a sky-ride to the top.", "yearEstablished": None},
    ],
    "HI": [
        {"name": "Haleakala National Park", "type": "national", "description": "A massive volcano on Maui with a moon-like crater at the summit.", "yearEstablished": 1916},
        {"name": "Pearl Harbor National Memorial", "type": "historic", "description": "Honors those lost in the December 7, 1941 attack.", "yearEstablished": 1980},
        {"name": "Puuhonua o Honaunau National Historical Park", "type": "historic", "description": "An ancient Hawaiian 'place of refuge' with carved wooden statues.", "yearEstablished": 1961},
        {"name": "Kaloko-Honokohau National Historical Park", "type": "historic", "description": "Preserves ancient Hawaiian fishponds and petroglyphs.", "yearEstablished": 1978},
        {"name": "Diamond Head State Monument", "type": "monument", "description": "A famous extinct volcanic crater near Waikiki.", "yearEstablished": 1968},
        {"name": "Waimea Canyon State Park", "type": "state", "description": "Often called the 'Grand Canyon of the Pacific'.", "yearEstablished": None},
        {"name": "Napali Coast State Wilderness Park", "type": "state", "description": "Towering green sea cliffs along Kauai's wild coast.", "yearEstablished": None},
        {"name": "Akaka Falls State Park", "type": "state", "description": "A 442-foot waterfall on the Big Island.", "yearEstablished": None},
        {"name": "Iolani Palace", "type": "historic", "description": "The only royal palace on U.S. soil.", "yearEstablished": None},
        {"name": "Polihale State Park", "type": "state", "description": "Remote western Kauai beach with massive sand dunes.", "yearEstablished": None},
    ],
    "ID": [
        {"name": "Craters of the Moon National Monument", "type": "monument", "description": "A vast lava field that looks like the surface of the moon.", "yearEstablished": 1924},
        {"name": "City of Rocks National Reserve", "type": "preserve", "description": "Famous granite spires used by California Trail pioneers.", "yearEstablished": 1988},
        {"name": "Hagerman Fossil Beds National Monument", "type": "monument", "description": "World-famous site for ancient horse fossils.", "yearEstablished": 1988},
        {"name": "Minidoka National Historic Site", "type": "historic", "description": "Honors Japanese Americans imprisoned here during WWII.", "yearEstablished": 2001},
        {"name": "Bruneau Dunes State Park", "type": "state", "description": "Home to North America's tallest single-structured sand dune.", "yearEstablished": 1970},
        {"name": "Ponderosa State Park", "type": "state", "description": "Forested peninsula jutting into Payette Lake.", "yearEstablished": 1908},
        {"name": "Heyburn State Park", "type": "state", "description": "The oldest state park in the Pacific Northwest.", "yearEstablished": 1908},
        {"name": "Farragut State Park", "type": "state", "description": "Once a WWII naval training base, now a lakeside playground.", "yearEstablished": 1965},
        {"name": "Harriman State Park", "type": "state", "description": "Famous for trumpeter swans and a historic cattle ranch.", "yearEstablished": 1977},
        {"name": "Thousand Springs State Park", "type": "state", "description": "Springs gushing from canyon walls along the Snake River.", "yearEstablished": None},
    ],
    "IL": [
        {"name": "Lincoln Home National Historic Site", "type": "historic", "description": "The only home Abraham Lincoln ever owned.", "yearEstablished": 1971},
        {"name": "Pullman National Historical Park", "type": "historic", "description": "A planned 1880s factory town and birthplace of the labor movement.", "yearEstablished": 2015},
        {"name": "Starved Rock State Park", "type": "state", "description": "Beautiful canyons and waterfalls along the Illinois River.", "yearEstablished": 1911},
        {"name": "Matthiessen State Park", "type": "state", "description": "Wooded canyon park with seasonal waterfalls.", "yearEstablished": 1943},
        {"name": "Garden of the Gods", "type": "state", "description": "Strange rock formations in the Shawnee National Forest.", "yearEstablished": None},
        {"name": "Giant City State Park", "type": "state", "description": "Sandstone bluffs that look like a giant city's streets.", "yearEstablished": 1927},
        {"name": "Cahokia Mounds State Historic Site", "type": "historic", "description": "Ancient earthwork mounds of a once-huge Native American city.", "yearEstablished": None},
        {"name": "Chain O'Lakes State Park", "type": "state", "description": "Park connecting three lakes great for boating and fishing.", "yearEstablished": 1945},
        {"name": "Mississippi Palisades State Park", "type": "state", "description": "High limestone bluffs along the Mississippi River.", "yearEstablished": None},
        {"name": "Pere Marquette State Park", "type": "state", "description": "Illinois's largest state park, great for fall colors.", "yearEstablished": 1932},
    ],
    "IN": [
        {"name": "Indiana Dunes National Park", "type": "national", "description": "Towering sand dunes along the shore of Lake Michigan.", "yearEstablished": 2019},
        {"name": "Lincoln Boyhood National Memorial", "type": "historic", "description": "The farm where young Abraham Lincoln grew up.", "yearEstablished": 1962},
        {"name": "George Rogers Clark National Historical Park", "type": "historic", "description": "Honors a key Revolutionary War victory in the West.", "yearEstablished": 1966},
        {"name": "Brown County State Park", "type": "state", "description": "Indiana's largest state park, famous for fall colors.", "yearEstablished": 1929},
        {"name": "Turkey Run State Park", "type": "state", "description": "Sandstone canyons and rope-assisted hiking trails.", "yearEstablished": 1916},
        {"name": "Indiana Dunes State Park", "type": "state", "description": "Tall sand dunes you can hike up for lake views.", "yearEstablished": 1925},
        {"name": "Spring Mill State Park", "type": "state", "description": "A restored pioneer village with a working grist mill.", "yearEstablished": 1927},
        {"name": "McCormick's Creek State Park", "type": "state", "description": "Indiana's first state park, with a beautiful waterfall.", "yearEstablished": 1916},
        {"name": "Clifty Falls State Park", "type": "state", "description": "Series of waterfalls and a deep, rugged canyon.", "yearEstablished": 1920},
        {"name": "Pokagon State Park", "type": "state", "description": "Famous for its quarter-mile-long refrigerated toboggan run.", "yearEstablished": 1925},
    ],
    "IA": [
        {"name": "Effigy Mounds National Monument", "type": "monument", "description": "Ancient earthen mounds shaped like bears and birds.", "yearEstablished": 1949},
        {"name": "Herbert Hoover National Historic Site", "type": "historic", "description": "Birthplace and library of America's 31st president.", "yearEstablished": 1965},
        {"name": "Maquoketa Caves State Park", "type": "state", "description": "More than a dozen caves to explore.", "yearEstablished": 1921},
        {"name": "Backbone State Park", "type": "state", "description": "Iowa's first state park, with limestone bluffs.", "yearEstablished": 1920},
        {"name": "Ledges State Park", "type": "state", "description": "Sandstone cliffs along Pea's Creek.", "yearEstablished": 1924},
        {"name": "Pikes Peak State Park", "type": "state", "description": "High bluff overlooking the Mississippi River.", "yearEstablished": 1928},
        {"name": "Wildcat Den State Park", "type": "state", "description": "Sandstone formations and a historic grist mill.", "yearEstablished": 1927},
        {"name": "Lake Macbride State Park", "type": "state", "description": "Iowa's largest state-owned lake, great for boating.", "yearEstablished": None},
        {"name": "Palisades-Kepler State Park", "type": "state", "description": "Limestone cliffs along the Cedar River.", "yearEstablished": None},
        {"name": "Stone State Park", "type": "state", "description": "Loess Hills park with sweeping prairie views.", "yearEstablished": 1935},
    ],
    "KS": [
        {"name": "Tallgrass Prairie National Preserve", "type": "preserve", "description": "Protects one of the last patches of tallgrass prairie in America.", "yearEstablished": 1996},
        {"name": "Nicodemus National Historic Site", "type": "historic", "description": "The only remaining Western town founded by formerly enslaved Black settlers.", "yearEstablished": 1996},
        {"name": "Fort Larned National Historic Site", "type": "historic", "description": "A well-preserved fort that protected the Santa Fe Trail.", "yearEstablished": 1964},
        {"name": "Brown v. Board of Education National Historical Park", "type": "historic", "description": "School at the heart of the landmark civil rights case.", "yearEstablished": 1992},
        {"name": "Monument Rocks", "type": "state", "description": "Chalk formations in the western Kansas prairie.", "yearEstablished": None},
        {"name": "Kanopolis State Park", "type": "state", "description": "Kansas's oldest state park with sandstone caves and canyons.", "yearEstablished": 1955},
        {"name": "Wilson State Park", "type": "state", "description": "Park surrounding 'the clearest lake in Kansas'.", "yearEstablished": 1965},
        {"name": "Tuttle Creek State Park", "type": "state", "description": "Big reservoir park great for boating and camping.", "yearEstablished": None},
        {"name": "Cheyenne Bottoms", "type": "preserve", "description": "Critical wetland stopover for migrating birds.", "yearEstablished": None},
        {"name": "Castle Rock", "type": "state", "description": "Towering chalk pillar in the high plains.", "yearEstablished": None},
    ],
    "KY": [
        {"name": "Mammoth Cave National Park", "type": "national", "description": "The longest known cave system on Earth.", "yearEstablished": 1941},
        {"name": "Cumberland Gap National Historical Park", "type": "historic", "description": "Mountain pass used by Daniel Boone and pioneers heading west.", "yearEstablished": 1940},
        {"name": "Abraham Lincoln Birthplace National Historical Park", "type": "historic", "description": "The Kentucky cabin site where Lincoln was born.", "yearEstablished": 1916},
        {"name": "Big South Fork National River", "type": "national", "description": "Wild river canyon with natural arches and old coal mines.", "yearEstablished": 1974},
        {"name": "Cumberland Falls State Resort Park", "type": "state", "description": "'Niagara of the South' famous for its rare moonbow.", "yearEstablished": 1931},
        {"name": "Natural Bridge State Resort Park", "type": "state", "description": "78-foot-long natural sandstone arch you can walk across.", "yearEstablished": 1926},
        {"name": "Red River Gorge", "type": "state", "description": "Sandstone cliffs and natural arches loved by rock climbers.", "yearEstablished": None},
        {"name": "Kentucky Horse Park", "type": "state", "description": "Working horse farm and museum celebrating all things horse.", "yearEstablished": 1978},
        {"name": "Carter Caves State Resort Park", "type": "state", "description": "More than 20 caves and a natural bridge.", "yearEstablished": None},
        {"name": "Lake Cumberland State Resort Park", "type": "state", "description": "Houseboat capital of the world on a huge man-made lake.", "yearEstablished": None},
    ],
    "LA": [
        {"name": "Jean Lafitte National Historical Park and Preserve", "type": "preserve", "description": "Cajun bayou wilderness named for a famous pirate.", "yearEstablished": 1978},
        {"name": "Cane River Creole National Historical Park", "type": "historic", "description": "Two cotton plantations preserving Creole culture.", "yearEstablished": 1994},
        {"name": "Poverty Point National Monument", "type": "monument", "description": "Ancient earthworks built 3,000 years ago.", "yearEstablished": 1988},
        {"name": "New Orleans Jazz National Historical Park", "type": "historic", "description": "Celebrates the birthplace of jazz music.", "yearEstablished": 1994},
        {"name": "Fontainebleau State Park", "type": "state", "description": "Beaches and bayou trails on Lake Pontchartrain.", "yearEstablished": 1942},
        {"name": "Chicot State Park", "type": "state", "description": "Louisiana's largest state park, with a cypress-tupelo lake.", "yearEstablished": 1939},
        {"name": "Bogue Chitto State Park", "type": "state", "description": "Sandbars and bluffs along a meandering blackwater river.", "yearEstablished": 2010},
        {"name": "Kisatchie National Forest", "type": "preserve", "description": "Louisiana's only national forest with rolling pine hills.", "yearEstablished": 1930},
        {"name": "Tickfaw State Park", "type": "state", "description": "Five different ecosystems connected by boardwalks.", "yearEstablished": 1999},
        {"name": "Lake Fausse Pointe State Park", "type": "state", "description": "Bald cypress swamp once part of the Atchafalaya Basin.", "yearEstablished": None},
    ],
    "ME": [
        {"name": "Katahdin Woods and Waters National Monument", "type": "monument", "description": "Wilderness of forests, rivers, and mountains near Mt. Katahdin.", "yearEstablished": 2016},
        {"name": "Saint Croix Island International Historic Site", "type": "historic", "description": "Site of one of the earliest French settlements in North America.", "yearEstablished": 1949},
        {"name": "Baxter State Park", "type": "state", "description": "Wilderness park with Mt. Katahdin, the highest point in Maine.", "yearEstablished": 1931},
        {"name": "Camden Hills State Park", "type": "state", "description": "Mount Battie views of Penobscot Bay.", "yearEstablished": 1947},
        {"name": "Reid State Park", "type": "state", "description": "Sandy ocean beach with tide pools.", "yearEstablished": 1946},
        {"name": "Two Lights State Park", "type": "state", "description": "Rocky Atlantic coast near famous twin lighthouses.", "yearEstablished": 1961},
        {"name": "Wolfe's Neck Woods State Park", "type": "state", "description": "Coastal forest with osprey nests.", "yearEstablished": None},
        {"name": "Quoddy Head State Park", "type": "state", "description": "Easternmost point in the contiguous U.S., with a candy-striped lighthouse.", "yearEstablished": None},
        {"name": "Sebago Lake State Park", "type": "state", "description": "Maine's second-largest lake, great for swimming.", "yearEstablished": 1938},
        {"name": "Grafton Notch State Park", "type": "state", "description": "Waterfalls and gorges in western Maine.", "yearEstablished": 1963},
    ],
    "MD": [
        {"name": "Assateague Island National Seashore", "type": "seashore", "description": "Wild Atlantic beaches famous for free-roaming ponies.", "yearEstablished": 1965},
        {"name": "Antietam National Battlefield", "type": "historic", "description": "Site of the bloodiest single day of the Civil War.", "yearEstablished": 1890},
        {"name": "Fort McHenry National Monument", "type": "monument", "description": "Star-shaped fort that inspired the Star-Spangled Banner.", "yearEstablished": 1925},
        {"name": "Harriet Tubman Underground Railroad National Historical Park", "type": "historic", "description": "Honors the famous abolitionist born in this region.", "yearEstablished": 2014},
        {"name": "Catoctin Mountain Park", "type": "national", "description": "Forested mountain park home to Camp David.", "yearEstablished": 1936},
        {"name": "Patapsco Valley State Park", "type": "state", "description": "Maryland's first state park with hiking, waterfalls, and history.", "yearEstablished": 1907},
        {"name": "Deep Creek Lake State Park", "type": "state", "description": "Maryland's largest inland lake, great for water sports.", "yearEstablished": 1959},
        {"name": "Swallow Falls State Park", "type": "state", "description": "Home to Maryland's tallest free-falling waterfall.", "yearEstablished": None},
        {"name": "Calvert Cliffs State Park", "type": "state", "description": "Beach famous for finding 15-million-year-old shark teeth.", "yearEstablished": None},
        {"name": "Rocky Gap State Park", "type": "state", "description": "Mountain lake park with a deep gorge.", "yearEstablished": None},
    ],
    "MA": [
        {"name": "Cape Cod National Seashore", "type": "seashore", "description": "40 miles of pristine sandy beaches on Cape Cod.", "yearEstablished": 1961},
        {"name": "Minute Man National Historical Park", "type": "historic", "description": "The road where the Revolutionary War began.", "yearEstablished": 1959},
        {"name": "Boston National Historical Park", "type": "historic", "description": "Includes the Freedom Trail and Old North Church.", "yearEstablished": 1974},
        {"name": "Lowell National Historical Park", "type": "historic", "description": "America's first planned industrial city.", "yearEstablished": 1978},
        {"name": "Adams National Historical Park", "type": "historic", "description": "Homes of Presidents John Adams and John Quincy Adams.", "yearEstablished": 1946},
        {"name": "Salem Maritime National Historic Site", "type": "historic", "description": "Tall ship and wharves of America's first national historic site.", "yearEstablished": 1938},
        {"name": "Mount Greylock State Reservation", "type": "state", "description": "Massachusetts's highest peak with a stone war memorial tower.", "yearEstablished": 1898},
        {"name": "Walden Pond State Reservation", "type": "state", "description": "Made famous by writer Henry David Thoreau.", "yearEstablished": 1922},
        {"name": "Mount Washington State Forest", "type": "state", "description": "Home to Bash Bish, Massachusetts's tallest waterfall.", "yearEstablished": None},
        {"name": "Nickerson State Park", "type": "state", "description": "Cape Cod park with eight crystal-clear kettle ponds.", "yearEstablished": None},
    ],
    "MI": [
        {"name": "Isle Royale National Park", "type": "national", "description": "Remote Lake Superior island with wolves and moose.", "yearEstablished": 1940},
        {"name": "Sleeping Bear Dunes National Lakeshore", "type": "seashore", "description": "Massive sand dunes towering 450 feet above Lake Michigan.", "yearEstablished": 1970},
        {"name": "Pictured Rocks National Lakeshore", "type": "seashore", "description": "Colorful sandstone cliffs along Lake Superior.", "yearEstablished": 1966},
        {"name": "Keweenaw National Historical Park", "type": "historic", "description": "Tells the story of Michigan's copper mining boom.", "yearEstablished": 1992},
        {"name": "Tahquamenon Falls State Park", "type": "state", "description": "Root beer-colored waterfall, one of the largest east of the Mississippi.", "yearEstablished": 1947},
        {"name": "Porcupine Mountains Wilderness State Park", "type": "state", "description": "Old-growth forest and the famous Lake of the Clouds.", "yearEstablished": 1944},
        {"name": "Mackinac Island State Park", "type": "state", "description": "Car-free island with Victorian charm and natural arches.", "yearEstablished": 1895},
        {"name": "Holland State Park", "type": "state", "description": "Beach park with Michigan's most famous lighthouse, 'Big Red'.", "yearEstablished": None},
        {"name": "Ludington State Park", "type": "state", "description": "Big Sable Point Lighthouse and rolling sand dunes.", "yearEstablished": 1934},
        {"name": "Warren Dunes State Park", "type": "state", "description": "Towering 260-foot dunes along Lake Michigan.", "yearEstablished": None},
    ],
    "MN": [
        {"name": "Voyageurs National Park", "type": "national", "description": "Northwoods water park best explored by canoe.", "yearEstablished": 1975},
        {"name": "Mississippi National River and Recreation Area", "type": "national", "description": "Protects the Mississippi as it flows through the Twin Cities.", "yearEstablished": 1988},
        {"name": "Pipestone National Monument", "type": "monument", "description": "Sacred quarry where Native Americans carve ceremonial pipes.", "yearEstablished": 1937},
        {"name": "Grand Portage National Monument", "type": "monument", "description": "Old fur trade fort on Lake Superior.", "yearEstablished": 1958},
        {"name": "Itasca State Park", "type": "state", "description": "Where you can walk across the headwaters of the Mississippi River.", "yearEstablished": 1891},
        {"name": "Gooseberry Falls State Park", "type": "state", "description": "Series of beautiful waterfalls along Lake Superior's North Shore.", "yearEstablished": 1937},
        {"name": "Tettegouche State Park", "type": "state", "description": "Cliffs, waterfalls, and inland lakes on Lake Superior.", "yearEstablished": 1979},
        {"name": "Split Rock Lighthouse State Park", "type": "state", "description": "Iconic 1910 lighthouse atop a 130-foot cliff.", "yearEstablished": 1971},
        {"name": "Jay Cooke State Park", "type": "state", "description": "St. Louis River rapids and a famous swinging bridge.", "yearEstablished": 1915},
        {"name": "Fort Snelling State Park", "type": "state", "description": "Where the Minnesota and Mississippi rivers meet.", "yearEstablished": 1961},
    ],
    "MS": [
        {"name": "Vicksburg National Military Park", "type": "historic", "description": "Site of the 47-day Civil War siege that turned the war.", "yearEstablished": 1899},
        {"name": "Gulf Islands National Seashore", "type": "seashore", "description": "Sugar-white sand beaches and barrier islands.", "yearEstablished": 1971},
        {"name": "Natchez Trace Parkway", "type": "national", "description": "Scenic 444-mile road tracing an ancient travel route.", "yearEstablished": 1938},
        {"name": "Natchez National Historical Park", "type": "historic", "description": "Three sites telling Natchez's antebellum and African American history.", "yearEstablished": 1988},
        {"name": "Tupelo National Battlefield", "type": "historic", "description": "Small park marking an 1864 Civil War battle.", "yearEstablished": 1929},
        {"name": "Tishomingo State Park", "type": "state", "description": "Massive boulders and a swinging bridge in the Appalachian foothills.", "yearEstablished": 1939},
        {"name": "Wall Doxey State Park", "type": "state", "description": "Spring-fed lake surrounded by towering hardwoods.", "yearEstablished": 1938},
        {"name": "Percy Quin State Park", "type": "state", "description": "Lakeside park with a championship golf course.", "yearEstablished": 1938},
        {"name": "Roosevelt State Park", "type": "state", "description": "Forested hills around Shadow Lake.", "yearEstablished": 1938},
        {"name": "Buccaneer State Park", "type": "state", "description": "Gulf Coast park named for the pirate Jean Lafitte.", "yearEstablished": 1973},
    ],
    "MO": [
        {"name": "Gateway Arch National Park", "type": "national", "description": "The 630-foot stainless steel arch in St. Louis.", "yearEstablished": 2018},
        {"name": "Ozark National Scenic Riverways", "type": "national", "description": "America's first national park to protect a wild river system.", "yearEstablished": 1964},
        {"name": "George Washington Carver National Monument", "type": "monument", "description": "Birthplace of the famous African American scientist.", "yearEstablished": 1943},
        {"name": "Wilson's Creek National Battlefield", "type": "historic", "description": "Site of the first major Civil War battle west of the Mississippi.", "yearEstablished": 1960},
        {"name": "Harry S Truman National Historic Site", "type": "historic", "description": "The home of America's 33rd president.", "yearEstablished": 1983},
        {"name": "Ha Ha Tonka State Park", "type": "state", "description": "Castle ruins atop bluffs above the Lake of the Ozarks.", "yearEstablished": 1978},
        {"name": "Elephant Rocks State Park", "type": "state", "description": "Giant pink granite boulders that look like a herd of elephants.", "yearEstablished": 1967},
        {"name": "Johnson's Shut-Ins State Park", "type": "state", "description": "Natural water-park canyon carved through volcanic rock.", "yearEstablished": 1955},
        {"name": "Meramec State Park", "type": "state", "description": "More than 40 caves along the Meramec River.", "yearEstablished": 1927},
        {"name": "Roaring River State Park", "type": "state", "description": "Spring-fed trout stream in a steep Ozark valley.", "yearEstablished": 1928},
    ],
    "MT": [
        {"name": "Glacier National Park", "type": "national", "description": "Carved by ancient glaciers, with the famous Going-to-the-Sun Road.", "yearEstablished": 1910},
        {"name": "Little Bighorn Battlefield National Monument", "type": "monument", "description": "Site of Custer's Last Stand.", "yearEstablished": 1879},
        {"name": "Big Hole National Battlefield", "type": "historic", "description": "Honors the Nez Perce War of 1877.", "yearEstablished": 1910},
        {"name": "Bighorn Canyon National Recreation Area", "type": "national", "description": "1,000-foot-deep canyon and wild horses.", "yearEstablished": 1966},
        {"name": "Grant-Kohrs Ranch National Historic Site", "type": "historic", "description": "A working cattle ranch preserving the cowboy era.", "yearEstablished": 1972},
        {"name": "Makoshika State Park", "type": "state", "description": "Montana's largest state park, full of dinosaur fossils.", "yearEstablished": 1953},
        {"name": "Lewis and Clark Caverns State Park", "type": "state", "description": "One of the largest limestone caverns in the Northwest.", "yearEstablished": 1937},
        {"name": "Bannack State Park", "type": "state", "description": "Montana's first gold-rush ghost town.", "yearEstablished": 1954},
        {"name": "Flathead Lake State Park", "type": "state", "description": "Largest natural freshwater lake west of the Mississippi.", "yearEstablished": None},
        {"name": "Pictograph Cave State Park", "type": "state", "description": "Ancient rock paintings made by Native Americans.", "yearEstablished": 1969},
    ],
    "NE": [
        {"name": "Scotts Bluff National Monument", "type": "monument", "description": "Towering bluff that guided wagon trains west.", "yearEstablished": 1919},
        {"name": "Agate Fossil Beds National Monument", "type": "monument", "description": "Fossils of ancient mammals from 20 million years ago.", "yearEstablished": 1965},
        {"name": "Homestead National Historical Park", "type": "historic", "description": "Honors the Homestead Act and pioneers who claimed free land.", "yearEstablished": 1936},
        {"name": "Niobrara National Scenic River", "type": "national", "description": "Wild river great for canoeing past waterfalls.", "yearEstablished": 1991},
        {"name": "Chimney Rock National Historic Site", "type": "historic", "description": "Famous spire on the Oregon and California Trails.", "yearEstablished": 1956},
        {"name": "Indian Cave State Park", "type": "state", "description": "Sandstone bluffs with ancient Native American petroglyphs.", "yearEstablished": 1962},
        {"name": "Platte River State Park", "type": "state", "description": "Wooded park on cliffs above the Platte River.", "yearEstablished": 1981},
        {"name": "Ponca State Park", "type": "state", "description": "Bluffs and oak forests on the Missouri River.", "yearEstablished": 1934},
        {"name": "Fort Robinson State Park", "type": "state", "description": "Historic frontier army post turned outdoor playground.", "yearEstablished": 1956},
        {"name": "Eugene T. Mahoney State Park", "type": "state", "description": "Family park with a giant observation tower and water playground.", "yearEstablished": 1991},
    ],
    "NV": [
        {"name": "Great Basin National Park", "type": "national", "description": "Ancient bristlecone pines and the Lehman Caves.", "yearEstablished": 1986},
        {"name": "Lake Mead National Recreation Area", "type": "national", "description": "America's largest reservoir behind Hoover Dam.", "yearEstablished": 1964},
        {"name": "Death Valley National Park", "type": "national", "description": "The hottest and lowest place in North America.", "yearEstablished": 1994},
        {"name": "Tule Springs Fossil Beds National Monument", "type": "monument", "description": "Ice Age fossils of mammoths and saber-toothed cats.", "yearEstablished": 2014},
        {"name": "Valley of Fire State Park", "type": "state", "description": "Nevada's oldest state park, full of red sandstone formations.", "yearEstablished": 1935},
        {"name": "Lake Tahoe Nevada State Park", "type": "state", "description": "Crystal-clear alpine lake on the Nevada-California border.", "yearEstablished": 1971},
        {"name": "Cathedral Gorge State Park", "type": "state", "description": "Dramatic clay spires carved by erosion.", "yearEstablished": 1935},
        {"name": "Berlin-Ichthyosaur State Park", "type": "state", "description": "Ghost town and 225-million-year-old marine reptile fossils.", "yearEstablished": 1957},
        {"name": "Spring Mountain Ranch State Park", "type": "state", "description": "Historic ranch in Red Rock Canyon.", "yearEstablished": 1974},
        {"name": "Sand Harbor", "type": "state", "description": "Lake Tahoe beach with crystal-clear coves.", "yearEstablished": None},
    ],
    "NH": [
        {"name": "Saint-Gaudens National Historical Park", "type": "historic", "description": "Home and studio of one of America's greatest sculptors.", "yearEstablished": 1964},
        {"name": "Franconia Notch State Park", "type": "state", "description": "Famous mountain pass and former home of the Old Man of the Mountain.", "yearEstablished": 1928},
        {"name": "Crawford Notch State Park", "type": "state", "description": "Steep mountain pass with the Arethusa Falls.", "yearEstablished": 1911},
        {"name": "Mount Monadnock State Park", "type": "state", "description": "One of the most-climbed mountains in the world.", "yearEstablished": None},
        {"name": "Mount Washington State Park", "type": "state", "description": "Highest peak in the Northeast, with the world's worst weather.", "yearEstablished": 1964},
        {"name": "Echo Lake State Park", "type": "state", "description": "Mountain lake with the famous Cathedral Ledge.", "yearEstablished": None},
        {"name": "Pawtuckaway State Park", "type": "state", "description": "Glacial boulder field and a stone tower.", "yearEstablished": None},
        {"name": "Bear Brook State Park", "type": "state", "description": "New Hampshire's largest state park with miles of trails.", "yearEstablished": None},
        {"name": "Hampton Beach State Park", "type": "state", "description": "Popular Atlantic Ocean beach with a boardwalk.", "yearEstablished": None},
        {"name": "Odiorne Point State Park", "type": "state", "description": "Rocky coastline with WWII bunkers and the Seacoast Science Center.", "yearEstablished": None},
    ],
    "NJ": [
        {"name": "Morristown National Historical Park", "type": "historic", "description": "America's first national historical park, where Washington's army camped.", "yearEstablished": 1933},
        {"name": "Thomas Edison National Historical Park", "type": "historic", "description": "The laboratory of America's greatest inventor.", "yearEstablished": 1955},
        {"name": "Gateway National Recreation Area", "type": "national", "description": "Beaches, forts, and Sandy Hook Lighthouse near New York Harbor.", "yearEstablished": 1972},
        {"name": "Pinelands National Reserve", "type": "preserve", "description": "Vast pine forest covering a million acres of South Jersey.", "yearEstablished": 1978},
        {"name": "Island Beach State Park", "type": "state", "description": "Ten miles of undeveloped barrier-island beach.", "yearEstablished": 1959},
        {"name": "High Point State Park", "type": "state", "description": "New Jersey's highest point, marked by a 220-foot obelisk.", "yearEstablished": 1923},
        {"name": "Wharton State Forest", "type": "state", "description": "Largest tract of public land in NJ, in the Pine Barrens.", "yearEstablished": None},
        {"name": "Liberty State Park", "type": "state", "description": "Park with stunning Statue of Liberty views.", "yearEstablished": 1976},
        {"name": "Allaire State Park", "type": "state", "description": "Restored 1830s iron-making village and steam railroad.", "yearEstablished": 1941},
        {"name": "Stokes State Forest", "type": "state", "description": "Mountain forest crossed by the Appalachian Trail.", "yearEstablished": 1907},
    ],
    "NM": [
        {"name": "Carlsbad Caverns National Park", "type": "national", "description": "Huge underground caves with hundreds of thousands of bats.", "yearEstablished": 1930},
        {"name": "White Sands National Park", "type": "national", "description": "Endless dunes of pure white gypsum sand you can sled on.", "yearEstablished": 2019},
        {"name": "Bandelier National Monument", "type": "monument", "description": "Ancient Pueblo cliff dwellings carved into volcanic rock.", "yearEstablished": 1916},
        {"name": "Chaco Culture National Historical Park", "type": "historic", "description": "Massive ancient Puebloan 'great houses'.", "yearEstablished": 1907},
        {"name": "Aztec Ruins National Monument", "type": "monument", "description": "900-year-old Ancestral Puebloan stone village.", "yearEstablished": 1923},
        {"name": "Gila Cliff Dwellings National Monument", "type": "monument", "description": "Cliff homes built by the Mogollon people 700 years ago.", "yearEstablished": 1907},
        {"name": "Petroglyph National Monument", "type": "monument", "description": "More than 24,000 ancient rock carvings near Albuquerque.", "yearEstablished": 1990},
        {"name": "Valles Caldera National Preserve", "type": "preserve", "description": "Giant collapsed volcano with elk-filled meadows.", "yearEstablished": 2000},
        {"name": "City of Rocks State Park", "type": "state", "description": "Volcanic rock formations standing like a city.", "yearEstablished": 1952},
        {"name": "Bottomless Lakes State Park", "type": "state", "description": "New Mexico's first state park, with deep blue sinkhole lakes.", "yearEstablished": 1933},
    ],
    "NY": [
        {"name": "Statue of Liberty National Monument", "type": "monument", "description": "France's famous gift welcoming people to America.", "yearEstablished": 1924},
        {"name": "Gateway National Recreation Area", "type": "national", "description": "Beaches and historic forts near New York Harbor.", "yearEstablished": 1972},
        {"name": "Fire Island National Seashore", "type": "seashore", "description": "Long Island's barrier-island beach with no cars.", "yearEstablished": 1964},
        {"name": "Saratoga National Historical Park", "type": "historic", "description": "Site of a Revolutionary War turning point.", "yearEstablished": 1938},
        {"name": "Women's Rights National Historical Park", "type": "historic", "description": "Birthplace of the American women's rights movement.", "yearEstablished": 1980},
        {"name": "Niagara Falls State Park", "type": "state", "description": "America's oldest state park, at the famous falls.", "yearEstablished": 1885},
        {"name": "Letchworth State Park", "type": "state", "description": "The 'Grand Canyon of the East' with three giant waterfalls.", "yearEstablished": 1907},
        {"name": "Watkins Glen State Park", "type": "state", "description": "A two-mile gorge with 19 waterfalls.", "yearEstablished": 1906},
        {"name": "Adirondack Park", "type": "state", "description": "Largest park in the contiguous U.S., bigger than Yellowstone.", "yearEstablished": 1892},
        {"name": "Catskill Park", "type": "state", "description": "Forested mountain park with hiking and waterfalls.", "yearEstablished": 1885},
    ],
    "NC": [
        {"name": "Great Smoky Mountains National Park", "type": "national", "description": "The most-visited national park in America.", "yearEstablished": 1934},
        {"name": "Cape Hatteras National Seashore", "type": "seashore", "description": "Outer Banks beaches and the tallest brick lighthouse in America.", "yearEstablished": 1937},
        {"name": "Cape Lookout National Seashore", "type": "seashore", "description": "Wild Outer Banks islands with wild horses.", "yearEstablished": 1966},
        {"name": "Wright Brothers National Memorial", "type": "historic", "description": "Where the Wright Brothers made the first powered flight.", "yearEstablished": 1927},
        {"name": "Carl Sandburg Home National Historic Site", "type": "historic", "description": "Home of the famous poet, with a goat dairy farm.", "yearEstablished": 1968},
        {"name": "Pisgah National Forest", "type": "preserve", "description": "Birthplace of American forestry, with waterfalls everywhere.", "yearEstablished": 1916},
        {"name": "Hanging Rock State Park", "type": "state", "description": "Granite peaks and waterfalls in the Sauratown Mountains.", "yearEstablished": 1936},
        {"name": "Mount Mitchell State Park", "type": "state", "description": "Site of the highest peak east of the Mississippi.", "yearEstablished": 1915},
        {"name": "Pilot Mountain State Park", "type": "state", "description": "A solitary stone pinnacle visible for miles.", "yearEstablished": 1968},
        {"name": "Jockey's Ridge State Park", "type": "state", "description": "Tallest natural sand dune system on the East Coast.", "yearEstablished": 1975},
    ],
    "ND": [
        {"name": "Theodore Roosevelt National Park", "type": "national", "description": "Badlands park where young Roosevelt fell in love with the West.", "yearEstablished": 1978},
        {"name": "Knife River Indian Villages National Historic Site", "type": "historic", "description": "Ancient Hidatsa and Mandan earth-lodge villages.", "yearEstablished": 1974},
        {"name": "Fort Union Trading Post National Historic Site", "type": "historic", "description": "Reconstructed 1800s fur trade fort.", "yearEstablished": 1966},
        {"name": "International Peace Garden", "type": "state", "description": "Garden park straddling the U.S.-Canada border.", "yearEstablished": 1932},
        {"name": "Lake Sakakawea State Park", "type": "state", "description": "Park on America's third-largest man-made lake.", "yearEstablished": 1965},
        {"name": "Cross Ranch State Park", "type": "state", "description": "One of the last free-flowing stretches of the Missouri River.", "yearEstablished": None},
        {"name": "Fort Abraham Lincoln State Park", "type": "state", "description": "Reconstructed Custer house and Mandan earth lodges.", "yearEstablished": 1907},
        {"name": "Lewis and Clark State Park", "type": "state", "description": "Park where Lewis and Clark camped along the Missouri.", "yearEstablished": None},
        {"name": "Icelandic State Park", "type": "state", "description": "Pioneer history museum and Lake Renwick.", "yearEstablished": None},
        {"name": "Turtle River State Park", "type": "state", "description": "Wooded riverside park great for hiking and skiing.", "yearEstablished": None},
    ],
    "OH": [
        {"name": "Cuyahoga Valley National Park", "type": "national", "description": "Forests, waterfalls, and a scenic railroad between Cleveland and Akron.", "yearEstablished": 2000},
        {"name": "Hopewell Culture National Historical Park", "type": "historic", "description": "Earthwork mounds of an ancient Native American culture.", "yearEstablished": 1923},
        {"name": "Dayton Aviation Heritage National Historical Park", "type": "historic", "description": "Honors the Wright Brothers' aviation breakthroughs.", "yearEstablished": 1992},
        {"name": "Perry's Victory and International Peace Memorial", "type": "monument", "description": "World's tallest Doric column on Lake Erie.", "yearEstablished": 1936},
        {"name": "James A. Garfield National Historic Site", "type": "historic", "description": "Home of America's 20th president.", "yearEstablished": 1980},
        {"name": "Hocking Hills State Park", "type": "state", "description": "Sandstone caves, cliffs, and waterfalls in a deep gorge.", "yearEstablished": 1924},
        {"name": "Cedar Point", "type": "state", "description": "Famous Lake Erie peninsula with roller coasters and beaches.", "yearEstablished": None},
        {"name": "Mohican State Park", "type": "state", "description": "Forested gorge popular for canoeing.", "yearEstablished": 1949},
        {"name": "John Bryan State Park", "type": "state", "description": "Beautiful Little Miami River gorge.", "yearEstablished": None},
        {"name": "Lake Erie Bluffs", "type": "state", "description": "Towering bluffs along Lake Erie's shore.", "yearEstablished": None},
    ],
    "OK": [
        {"name": "Chickasaw National Recreation Area", "type": "national", "description": "Mineral springs and a clear-water lake in the Arbuckle Mountains.", "yearEstablished": 1976},
        {"name": "Washita Battlefield National Historic Site", "type": "historic", "description": "Site of an 1868 Cheyenne village attack.", "yearEstablished": 1996},
        {"name": "Oklahoma City National Memorial", "type": "monument", "description": "Honors the victims of the 1995 bombing.", "yearEstablished": 1997},
        {"name": "Fort Smith National Historic Site", "type": "historic", "description": "Frontier fort that became the courtroom of 'Hanging Judge' Parker.", "yearEstablished": 1961},
        {"name": "Beavers Bend State Park", "type": "state", "description": "Pine forests and crystal-clear Mountain Fork River.", "yearEstablished": 1937},
        {"name": "Robbers Cave State Park", "type": "state", "description": "Once a hideout for outlaws like Jesse James.", "yearEstablished": 1935},
        {"name": "Quartz Mountain State Park", "type": "state", "description": "1.4-billion-year-old granite mountains.", "yearEstablished": 1937},
        {"name": "Roman Nose State Park", "type": "state", "description": "Canyons and crystal-clear springs.", "yearEstablished": 1937},
        {"name": "Black Mesa State Park", "type": "state", "description": "Sits at Oklahoma's highest point in the panhandle.", "yearEstablished": 1959},
        {"name": "Lake Murray State Park", "type": "state", "description": "Oklahoma's largest state park.", "yearEstablished": 1933},
    ],
    "OR": [
        {"name": "Crater Lake National Park", "type": "national", "description": "America's deepest lake, formed inside a volcano.", "yearEstablished": 1902},
        {"name": "Lewis and Clark National Historical Park", "type": "historic", "description": "Where Lewis and Clark wintered after reaching the Pacific.", "yearEstablished": 2004},
        {"name": "Oregon Caves National Monument", "type": "monument", "description": "Marble caves with rare formations.", "yearEstablished": 1909},
        {"name": "John Day Fossil Beds National Monument", "type": "monument", "description": "Colorful badlands holding 40 million years of fossils.", "yearEstablished": 1975},
        {"name": "Newberry National Volcanic Monument", "type": "monument", "description": "Massive volcano with obsidian flows and lakes.", "yearEstablished": 1990},
        {"name": "Silver Falls State Park", "type": "state", "description": "'Crown jewel' of Oregon parks with ten waterfalls.", "yearEstablished": 1933},
        {"name": "Smith Rock State Park", "type": "state", "description": "Birthplace of American sport rock climbing.", "yearEstablished": 1960},
        {"name": "Ecola State Park", "type": "state", "description": "Iconic Pacific Coast views of Haystack Rock.", "yearEstablished": 1932},
        {"name": "Cape Lookout State Park", "type": "state", "description": "Forested headland jutting into the Pacific.", "yearEstablished": None},
        {"name": "Oswald West State Park", "type": "state", "description": "Old-growth coastal rainforest above secluded Short Sand Beach.", "yearEstablished": None},
    ],
    "PA": [
        {"name": "Gettysburg National Military Park", "type": "historic", "description": "Site of the most famous battle of the Civil War.", "yearEstablished": 1895},
        {"name": "Independence National Historical Park", "type": "historic", "description": "Home of Independence Hall and the Liberty Bell.", "yearEstablished": 1948},
        {"name": "Valley Forge National Historical Park", "type": "historic", "description": "Washington's army's winter camp during the Revolution.", "yearEstablished": 1976},
        {"name": "Allegheny Portage Railroad National Historic Site", "type": "historic", "description": "Engineering wonder that climbed the Allegheny Mountains.", "yearEstablished": 1964},
        {"name": "Flight 93 National Memorial", "type": "historic", "description": "Honors the heroes of United Flight 93 on 9/11.", "yearEstablished": 2002},
        {"name": "Fort Necessity National Battlefield", "type": "historic", "description": "Site of the first battle of the French and Indian War.", "yearEstablished": 1933},
        {"name": "Ricketts Glen State Park", "type": "state", "description": "21 named waterfalls in a glacial gorge.", "yearEstablished": 1944},
        {"name": "Ohiopyle State Park", "type": "state", "description": "Whitewater capital of the East on the Youghiogheny River.", "yearEstablished": 1965},
        {"name": "Presque Isle State Park", "type": "state", "description": "Sandy peninsula jutting into Lake Erie.", "yearEstablished": 1921},
        {"name": "Cherry Springs State Park", "type": "state", "description": "One of the darkest skies in the eastern U.S., perfect for stargazing.", "yearEstablished": 1922},
    ],
    "RI": [
        {"name": "Roger Williams National Memorial", "type": "historic", "description": "Honors the founder of Rhode Island and religious freedom.", "yearEstablished": 1965},
        {"name": "Blackstone River Valley National Historical Park", "type": "historic", "description": "Birthplace of America's Industrial Revolution.", "yearEstablished": 2014},
        {"name": "Colt State Park", "type": "state", "description": "'The gem of Rhode Island's state parks' on Narragansett Bay.", "yearEstablished": 1965},
        {"name": "Lincoln Woods State Park", "type": "state", "description": "Wooded park with a pond for swimming.", "yearEstablished": None},
        {"name": "Beavertail State Park", "type": "state", "description": "One of the oldest lighthouses in America at the tip of Conanicut Island.", "yearEstablished": None},
        {"name": "Burlingame State Park", "type": "state", "description": "Camping park on Watchaug Pond.", "yearEstablished": None},
        {"name": "Goddard Memorial State Park", "type": "state", "description": "Forested park with a saltwater beach.", "yearEstablished": None},
    ],
    "SC": [
        {"name": "Congaree National Park", "type": "national", "description": "Largest old-growth bottomland hardwood forest in the U.S.", "yearEstablished": 2003},
        {"name": "Fort Sumter and Fort Moultrie National Historical Park", "type": "historic", "description": "Where the Civil War began.", "yearEstablished": 1948},
        {"name": "Cowpens National Battlefield", "type": "historic", "description": "Site of a key Revolutionary War victory.", "yearEstablished": 1929},
        {"name": "Kings Mountain National Military Park", "type": "historic", "description": "Site of a turning-point Revolutionary War battle.", "yearEstablished": 1931},
        {"name": "Charles Pinckney National Historic Site", "type": "historic", "description": "Home of a signer of the Constitution.", "yearEstablished": 1988},
        {"name": "Hunting Island State Park", "type": "state", "description": "South Carolina's most-visited state park, with a climbable lighthouse.", "yearEstablished": 1938},
        {"name": "Myrtle Beach State Park", "type": "state", "description": "Maritime forest right on the Atlantic Ocean.", "yearEstablished": 1936},
        {"name": "Caesars Head State Park", "type": "state", "description": "Mountain overlook with sweeping views of the Blue Ridge.", "yearEstablished": None},
        {"name": "Table Rock State Park", "type": "state", "description": "Named for the granite dome that looms over Pinnacle Lake.", "yearEstablished": 1935},
        {"name": "Edisto Beach State Park", "type": "state", "description": "Sea Island beach famous for shark teeth.", "yearEstablished": 1935},
    ],
    "SD": [
        {"name": "Wind Cave National Park", "type": "national", "description": "One of the world's longest and most complex caves.", "yearEstablished": 1903},
        {"name": "Mount Rushmore National Memorial", "type": "monument", "description": "Four giant presidents carved into the Black Hills.", "yearEstablished": 1925},
        {"name": "Jewel Cave National Monument", "type": "monument", "description": "Third-longest cave in the world.", "yearEstablished": 1908},
        {"name": "Minuteman Missile National Historic Site", "type": "historic", "description": "Cold War nuclear missile silo and control center.", "yearEstablished": 1999},
        {"name": "Custer State Park", "type": "state", "description": "Famous for its herd of 1,300 free-roaming bison.", "yearEstablished": 1912},
        {"name": "Bear Butte State Park", "type": "state", "description": "Sacred mountain to many Plains tribes.", "yearEstablished": 1961},
        {"name": "Newton Hills State Park", "type": "state", "description": "Wooded ridge in southeastern South Dakota.", "yearEstablished": 1947},
        {"name": "Palisades State Park", "type": "state", "description": "Sioux quartzite cliffs along Split Rock Creek.", "yearEstablished": 1933},
        {"name": "Lewis and Clark Recreation Area", "type": "state", "description": "Big reservoir park on the Missouri River.", "yearEstablished": None},
        {"name": "Roughlock Falls", "type": "state", "description": "Beautiful waterfall in Spearfish Canyon.", "yearEstablished": None},
    ],
    "TN": [
        {"name": "Great Smoky Mountains National Park", "type": "national", "description": "Misty mountains shared with North Carolina, the most visited national park.", "yearEstablished": 1934},
        {"name": "Big South Fork National River", "type": "national", "description": "Wild river canyon with natural arches.", "yearEstablished": 1974},
        {"name": "Shiloh National Military Park", "type": "historic", "description": "Site of one of the bloodiest Civil War battles.", "yearEstablished": 1894},
        {"name": "Andrew Johnson National Historic Site", "type": "historic", "description": "Home and tailor shop of America's 17th president.", "yearEstablished": 1942},
        {"name": "Manhattan Project National Historical Park", "type": "historic", "description": "Oak Ridge site that helped build the atomic bomb.", "yearEstablished": 2015},
        {"name": "Fall Creek Falls State Park", "type": "state", "description": "Home to one of the tallest waterfalls east of the Mississippi.", "yearEstablished": 1937},
        {"name": "Cumberland Mountain State Park", "type": "state", "description": "CCC-built park with the largest masonry dam they made.", "yearEstablished": 1938},
        {"name": "Roan Mountain State Park", "type": "state", "description": "Famous for natural rhododendron gardens at 6,000 feet.", "yearEstablished": 1950},
        {"name": "Reelfoot Lake State Park", "type": "state", "description": "Lake formed by an 1811 earthquake, full of cypress trees.", "yearEstablished": 1956},
        {"name": "Burgess Falls State Park", "type": "state", "description": "Four waterfalls in less than a mile.", "yearEstablished": 1971},
    ],
    "TX": [
        {"name": "Big Bend National Park", "type": "national", "description": "Vast desert, river canyons, and mountains on the Rio Grande.", "yearEstablished": 1944},
        {"name": "Guadalupe Mountains National Park", "type": "national", "description": "Site of Texas's highest peak and ancient marine fossils.", "yearEstablished": 1972},
        {"name": "Padre Island National Seashore", "type": "seashore", "description": "Longest undeveloped barrier island in the world.", "yearEstablished": 1962},
        {"name": "San Antonio Missions National Historical Park", "type": "historic", "description": "Four Spanish missions including the famous Alamo.", "yearEstablished": 1978},
        {"name": "Lyndon B. Johnson National Historical Park", "type": "historic", "description": "Boyhood home and 'Texas White House' of the 36th president.", "yearEstablished": 1969},
        {"name": "Waco Mammoth National Monument", "type": "monument", "description": "Fossil bed of an Ice Age mammoth herd.", "yearEstablished": 2015},
        {"name": "Palo Duro Canyon State Park", "type": "state", "description": "The 'Grand Canyon of Texas', second-largest in the U.S.", "yearEstablished": 1934},
        {"name": "Enchanted Rock State Natural Area", "type": "state", "description": "Massive pink granite dome you can hike to the top of.", "yearEstablished": 1978},
        {"name": "Garner State Park", "type": "state", "description": "Texas's most popular state park on the Frio River.", "yearEstablished": 1941},
        {"name": "Caddo Lake State Park", "type": "state", "description": "Mysterious cypress swamp on the Texas-Louisiana border.", "yearEstablished": 1934},
    ],
    "UT": [
        {"name": "Grand Staircase-Escalante National Monument", "type": "monument", "description": "Vast wilderness of cliffs, slot canyons, and dinosaur fossils.", "yearEstablished": 1996},
        {"name": "Cedar Breaks National Monument", "type": "monument", "description": "Half-mile-deep natural amphitheater of red and orange rock.", "yearEstablished": 1933},
        {"name": "Natural Bridges National Monument", "type": "monument", "description": "Three of the world's largest natural stone bridges.", "yearEstablished": 1908},
        {"name": "Dinosaur National Monument", "type": "monument", "description": "Quarry wall studded with real dinosaur bones.", "yearEstablished": 1915},
        {"name": "Goblin Valley State Park", "type": "state", "description": "Field of mushroom-shaped 'goblin' rocks kids can run through.", "yearEstablished": 1964},
        {"name": "Dead Horse Point State Park", "type": "state", "description": "Dramatic overlook 2,000 feet above the Colorado River.", "yearEstablished": 1959},
        {"name": "Snow Canyon State Park", "type": "state", "description": "Red and white sandstone canyon near St. George.", "yearEstablished": 1959},
        {"name": "Coral Pink Sand Dunes State Park", "type": "state", "description": "Salmon-colored dunes you can sandboard down.", "yearEstablished": 1963},
        {"name": "Sand Hollow State Park", "type": "state", "description": "Bright blue reservoir surrounded by red sandstone.", "yearEstablished": 2003},
        {"name": "Kodachrome Basin State Park", "type": "state", "description": "67 colorful sand pipes that look like petrified geysers.", "yearEstablished": 1962},
    ],
    "VT": [
        {"name": "Marsh-Billings-Rockefeller National Historical Park", "type": "historic", "description": "Vermont's only national park, honoring conservation pioneers.", "yearEstablished": 1992},
        {"name": "Appalachian National Scenic Trail", "type": "national", "description": "Section of the 2,200-mile trail running through Vermont.", "yearEstablished": 1968},
        {"name": "Mount Mansfield State Forest", "type": "state", "description": "Vermont's highest peak with a long ridge you can hike.", "yearEstablished": None},
        {"name": "Smugglers' Notch State Park", "type": "state", "description": "Mountain pass once used by smugglers and the Underground Railroad.", "yearEstablished": 1933},
        {"name": "Quechee State Park", "type": "state", "description": "Vermont's 'Little Grand Canyon', 165 feet deep.", "yearEstablished": 1965},
        {"name": "Camel's Hump State Park", "type": "state", "description": "Iconic humped mountain visible from across Vermont.", "yearEstablished": None},
        {"name": "Mt. Philo State Park", "type": "state", "description": "Vermont's oldest state park, with Lake Champlain views.", "yearEstablished": 1924},
        {"name": "Button Bay State Park", "type": "state", "description": "Lake Champlain park named for round stone 'buttons'.", "yearEstablished": None},
        {"name": "Grand Isle State Park", "type": "state", "description": "Island park in the middle of Lake Champlain.", "yearEstablished": None},
        {"name": "Little River State Park", "type": "state", "description": "Camping park near a flooded 1800s farming community.", "yearEstablished": None},
    ],
    "VA": [
        {"name": "Shenandoah National Park", "type": "national", "description": "Mountain park along scenic Skyline Drive.", "yearEstablished": 1935},
        {"name": "Colonial National Historical Park", "type": "historic", "description": "Includes Jamestown and Yorktown, key American history sites.", "yearEstablished": 1936},
        {"name": "Manassas National Battlefield Park", "type": "historic", "description": "Site of two major Civil War battles.", "yearEstablished": 1940},
        {"name": "Appomattox Court House National Historical Park", "type": "historic", "description": "Where the Civil War ended.", "yearEstablished": 1940},
        {"name": "Arlington House", "type": "historic", "description": "Robert E. Lee's mansion above Arlington National Cemetery.", "yearEstablished": 1925},
        {"name": "Booker T. Washington National Monument", "type": "monument", "description": "Birthplace of the famous African American educator.", "yearEstablished": 1956},
        {"name": "Assateague Island National Seashore", "type": "seashore", "description": "Wild Atlantic beaches with free-roaming ponies.", "yearEstablished": 1965},
        {"name": "First Landing State Park", "type": "state", "description": "Site where English colonists first landed in 1607.", "yearEstablished": 1936},
        {"name": "Grayson Highlands State Park", "type": "state", "description": "Home to wild ponies in the Virginia highlands.", "yearEstablished": 1965},
        {"name": "Natural Bridge State Park", "type": "state", "description": "215-foot natural limestone arch once owned by Thomas Jefferson.", "yearEstablished": 2016},
    ],
    "WA": [
        {"name": "Mount Rainier National Park", "type": "national", "description": "Towering glacier-clad volcano you can see from Seattle.", "yearEstablished": 1899},
        {"name": "Olympic National Park", "type": "national", "description": "Rainforests, mountains, and wild Pacific coast all in one park.", "yearEstablished": 1938},
        {"name": "North Cascades National Park", "type": "national", "description": "Jagged peaks and over 300 glaciers.", "yearEstablished": 1968},
        {"name": "Mount St. Helens National Volcanic Monument", "type": "monument", "description": "Volcano that famously erupted in 1980.", "yearEstablished": 1982},
        {"name": "San Juan Island National Historical Park", "type": "historic", "description": "Site of a bloodless border dispute called the 'Pig War'.", "yearEstablished": 1966},
        {"name": "Whitman Mission National Historic Site", "type": "historic", "description": "Early Oregon Trail mission site.", "yearEstablished": 1936},
        {"name": "Deception Pass State Park", "type": "state", "description": "Washington's most-visited state park, with a dramatic bridge.", "yearEstablished": 1923},
        {"name": "Cape Disappointment State Park", "type": "state", "description": "Where Lewis and Clark reached the Pacific.", "yearEstablished": 1965},
        {"name": "Mount Spokane State Park", "type": "state", "description": "Washington's largest state park, with a summit lodge.", "yearEstablished": 1927},
        {"name": "Palouse Falls State Park", "type": "state", "description": "Washington's official state waterfall, 200 feet tall.", "yearEstablished": 1951},
    ],
    "WV": [
        {"name": "New River Gorge National Park", "type": "national", "description": "America's newest national park, famous for whitewater and a giant bridge.", "yearEstablished": 2020},
        {"name": "Harpers Ferry National Historical Park", "type": "historic", "description": "Where two rivers meet and John Brown's raid sparked the Civil War.", "yearEstablished": 1944},
        {"name": "Bluestone National Scenic River", "type": "national", "description": "Wild river through a remote Appalachian gorge.", "yearEstablished": 1988},
        {"name": "Gauley River National Recreation Area", "type": "national", "description": "World-class whitewater river.", "yearEstablished": 1988},
        {"name": "Blackwater Falls State Park", "type": "state", "description": "Famous amber-colored waterfall in a deep gorge.", "yearEstablished": 1937},
        {"name": "Babcock State Park", "type": "state", "description": "Home to the much-photographed Glade Creek Grist Mill.", "yearEstablished": 1937},
        {"name": "Hawks Nest State Park", "type": "state", "description": "Overlook 750 feet above the New River with a tramway.", "yearEstablished": None},
        {"name": "Seneca Rocks", "type": "state", "description": "Famous quartzite climbing crag, 900 feet tall.", "yearEstablished": None},
        {"name": "Cass Scenic Railroad State Park", "type": "state", "description": "Ride a restored logging steam train up Bald Knob.", "yearEstablished": 1963},
        {"name": "Pipestem Resort State Park", "type": "state", "description": "Includes an aerial tramway down to the Bluestone Gorge.", "yearEstablished": 1970},
    ],
    "WI": [
        {"name": "Apostle Islands National Lakeshore", "type": "seashore", "description": "21 wild islands and famous sea caves in Lake Superior.", "yearEstablished": 1970},
        {"name": "Saint Croix National Scenic Riverway", "type": "national", "description": "Wild river forming the Minnesota border.", "yearEstablished": 1968},
        {"name": "Ice Age National Scenic Trail", "type": "national", "description": "1,200-mile trail along the edge of the last great glacier.", "yearEstablished": 1980},
        {"name": "Devil's Lake State Park", "type": "state", "description": "Wisconsin's most-visited state park, with 500-foot quartzite bluffs.", "yearEstablished": 1911},
        {"name": "Peninsula State Park", "type": "state", "description": "Door County peninsula park with a famous lighthouse.", "yearEstablished": 1909},
        {"name": "Wyalusing State Park", "type": "state", "description": "Where the Wisconsin and Mississippi rivers meet.", "yearEstablished": 1917},
        {"name": "Interstate State Park", "type": "state", "description": "Wisconsin's oldest state park, with deep glacial potholes.", "yearEstablished": 1900},
        {"name": "Pattison State Park", "type": "state", "description": "Home to Big Manitou Falls, Wisconsin's tallest waterfall.", "yearEstablished": 1920},
        {"name": "Copper Falls State Park", "type": "state", "description": "Series of waterfalls cutting through ancient lava.", "yearEstablished": 1929},
        {"name": "Willow River State Park", "type": "state", "description": "Beautiful Willow Falls and a swimming pond.", "yearEstablished": 1971},
    ],
    "WY": [
        {"name": "Grand Teton National Park", "type": "national", "description": "Jagged peaks rising straight up from the valley floor.", "yearEstablished": 1929},
        {"name": "Devils Tower National Monument", "type": "monument", "description": "America's first national monument, a sacred volcanic tower.", "yearEstablished": 1906},
        {"name": "Fossil Butte National Monument", "type": "monument", "description": "Ancient lake bed with thousands of fossil fish.", "yearEstablished": 1972},
        {"name": "Fort Laramie National Historic Site", "type": "historic", "description": "Frontier fort that protected the Oregon Trail.", "yearEstablished": 1938},
        {"name": "Bighorn Canyon National Recreation Area", "type": "national", "description": "1,000-foot-deep canyon with wild horses.", "yearEstablished": 1966},
        {"name": "Sinks Canyon State Park", "type": "state", "description": "River that flows into a cave and reappears a quarter-mile away.", "yearEstablished": 1971},
        {"name": "Curt Gowdy State Park", "type": "state", "description": "Three lakes and giant granite boulders.", "yearEstablished": 1971},
        {"name": "Hot Springs State Park", "type": "state", "description": "One of the world's largest mineral hot springs.", "yearEstablished": 1897},
        {"name": "Boysen State Park", "type": "state", "description": "Big reservoir park at the entrance to Wind River Canyon.", "yearEstablished": None},
        {"name": "Buffalo Bill State Park", "type": "state", "description": "Park around Buffalo Bill Dam near Cody.", "yearEstablished": None},
    ],
}


def main():
    with STATES_PATH.open("r", encoding="utf-8") as f:
        states = json.load(f)

    size_before = STATES_PATH.stat().st_size
    total_before = sum(len(s["parks"]) for s in states)

    for state in states:
        postal = state["postal"]
        existing = state["parks"]
        existing_names = {p["name"].strip().lower() for p in existing}
        additions = ADDITIONS.get(postal, [])
        for new_park in additions:
            if new_park["name"].strip().lower() in existing_names:
                continue
            if len(existing) >= MAX_PARKS:
                break
            existing.append(new_park)
            existing_names.add(new_park["name"].strip().lower())

    with STATES_PATH.open("w", encoding="utf-8") as f:
        json.dump(states, f, indent=2, ensure_ascii=False)

    size_after = STATES_PATH.stat().st_size
    total_after = sum(len(s["parks"]) for s in states)
    print(f"states: {len(states)}")
    print(f"total parks before: {total_before}")
    print(f"total parks after: {total_after}")
    print(f"avg per state: {total_after / len(states):.2f}")
    print(f"file size before: {size_before:,} bytes")
    print(f"file size after: {size_after:,} bytes")


if __name__ == "__main__":
    main()
