// AUTO-GENERATED chore catalog merged from the family spreadsheets
// (Family_Job_List.xlsx + skylight_chores.js). 171 jobs across 22 rooms,
// incl. oil changes (car + van). Source files live in ~/Documents/jobs.
// Edit/extend freely — this is just the starter set a new family can load.
//
// Each entry: { room, name, frequency }. MP defaults from frequency at
// seed time (DEFAULT_MP_BY_FREQUENCY). Used by scripts/seed-family-chores.mjs.

import type { Frequency } from '@/lib/family/types';

export interface CatalogJob { room: string; name: string; frequency: Frequency; }

export const CHORE_CATALOG: CatalogJob[] = [
  { room: 'Front Room', name: 'floor', frequency: 'daily' },
  { room: 'Front Room', name: 'Vacuume', frequency: 'weekly' },
  { room: 'Front Room', name: 'Clean piano', frequency: 'monthly' },
  { room: 'Front Room', name: 'fix couch coushions', frequency: 'monthly' },
  { room: 'Front Room', name: 'dust mid boards', frequency: 'monthly' },
  { room: 'Front Room', name: 'dust base boards', frequency: 'monthly' },
  { room: 'Front Room', name: 'clean door knob', frequency: 'monthly' },
  { room: 'Front Room', name: 'light switches', frequency: 'monthly' },
  { room: 'Front Room', name: 'Wash walls', frequency: 'quarterly' },
  { room: 'Coat Room', name: 'Orginize wood', frequency: 'weekly' },
  { room: 'Coat Room', name: 'hang things up', frequency: 'weekly' },
  { room: 'Coat Room', name: 'Clean floor', frequency: 'weekly' },
  { room: 'Coat Room', name: 'Sweep floor', frequency: 'weekly' },
  { room: 'Coat Room', name: 'Mop floor', frequency: 'weekly' },
  { room: 'Coat Room', name: 'door knobs', frequency: 'monthly' },
  { room: 'Coat Room', name: 'light switches', frequency: 'monthly' },
  { room: 'Kitchen', name: 'pick up tile', frequency: 'daily' },
  { room: 'Kitchen', name: 'dinner', frequency: 'daily' },
  { room: 'Kitchen', name: 'unload dishwasher', frequency: 'daily' },
  { room: 'Kitchen', name: 'load dishwasher', frequency: 'daily' },
  { room: 'Kitchen', name: 'Clean off Table', frequency: 'weekly' },
  { room: 'Kitchen', name: 'srub table', frequency: 'weekly' },
  { room: 'Kitchen', name: 'sweep tile', frequency: 'weekly' },
  { room: 'Kitchen', name: 'mop tile', frequency: 'weekly' },
  { room: 'Kitchen', name: 'clean off oven', frequency: 'weekly' },
  { room: 'Kitchen', name: 'scrub oven', frequency: 'quarterly' },
  { room: 'Kitchen', name: 'Scrub fridge', frequency: 'quarterly' },
  { room: 'Kitchen', name: 'scrub dish washer', frequency: 'quarterly' },
  { room: 'Living Room', name: 'books', frequency: 'daily' },
  { room: 'Living Room', name: 'blankets', frequency: 'daily' },
  { room: 'Living Room', name: 'ding ding dings', frequency: 'daily' },
  { room: 'Living Room', name: 'Clean floor', frequency: 'weekly' },
  { room: 'Living Room', name: 'vacuume', frequency: 'weekly' },
  { room: 'Living Room', name: 'Clean fire place', frequency: 'weekly' },
  { room: 'Living Room', name: 'dust fire place', frequency: 'monthly' },
  { room: 'Living Room', name: 'dust ceiling fan', frequency: 'monthly' },
  { room: 'Living Room', name: 'wash door knobs', frequency: 'monthly' },
  { room: 'Living Room', name: 'light switches', frequency: 'monthly' },
  { room: 'Living Room', name: 'wash walls', frequency: 'quarterly' },
  { room: 'Guest Bathroom', name: 'toilet', frequency: 'daily' },
  { room: 'Guest Bathroom', name: 'pick up floor', frequency: 'daily' },
  { room: 'Guest Bathroom', name: 'sweep tile', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'Mop tile', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'scrub tub', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'mirir', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'clean off counter', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'wash counter', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'wash sink', frequency: 'weekly' },
  { room: 'Guest Bathroom', name: 'Garbage can', frequency: 'weekly' },
  { room: 'Stairs', name: 'pick up stairs', frequency: 'daily' },
  { room: 'Stairs', name: 'vacuume', frequency: 'weekly' },
  { room: 'Upstairs Living Room', name: 'Clean floor', frequency: 'weekly' },
  { room: 'Upstairs Living Room', name: 'Couch coussions', frequency: 'weekly' },
  { room: 'Upstairs Living Room', name: 'vacuume', frequency: 'weekly' },
  { room: 'Upstairs Living Room', name: 'door knobs', frequency: 'monthly' },
  { room: 'Upstairs Living Room', name: 'Light switches', frequency: 'monthly' },
  { room: 'Upstairs Living Room', name: 'Cielling fan', frequency: 'monthly' },
  { room: 'Upstairs Living Room', name: 'wash walls', frequency: 'quarterly' },
  { room: 'Boys Bedroom', name: 'floor', frequency: 'daily' },
  { room: 'Boys Bedroom', name: 'cloths', frequency: 'daily' },
  { room: 'Boys Bedroom', name: 'bring clothes down', frequency: 'daily' },
  { room: 'Boys Bedroom', name: 'clean up closet', frequency: 'weekly' },
  { room: 'Boys Bedroom', name: 'vacuume', frequency: 'weekly' },
  { room: 'Boys Bedroom', name: 'Clean off dresser', frequency: 'weekly' },
  { room: 'Boys Bedroom', name: 'clean under bed', frequency: 'monthly' },
  { room: 'Girls Bedroom', name: 'floor', frequency: 'daily' },
  { room: 'Girls Bedroom', name: 'cloths', frequency: 'daily' },
  { room: 'Girls Bedroom', name: 'bring clothes down', frequency: 'daily' },
  { room: 'Girls Bedroom', name: 'clean up closet', frequency: 'weekly' },
  { room: 'Girls Bedroom', name: 'vacuume', frequency: 'weekly' },
  { room: 'Girls Bedroom', name: 'Clean off dresser', frequency: 'weekly' },
  { room: 'Girls Bedroom', name: 'clean under bed', frequency: 'monthly' },
  { room: 'Spare Bedroom', name: 'floor', frequency: 'daily' },
  { room: 'Spare Bedroom', name: 'cloths', frequency: 'daily' },
  { room: 'Spare Bedroom', name: 'bring clothes down', frequency: 'daily' },
  { room: 'Spare Bedroom', name: 'clean up closet', frequency: 'weekly' },
  { room: 'Spare Bedroom', name: 'vacuume', frequency: 'weekly' },
  { room: 'Spare Bedroom', name: 'Clean off dresser', frequency: 'weekly' },
  { room: 'Spare Bedroom', name: 'clean under bed', frequency: 'monthly' },
  { room: 'Up Bathroom', name: 'toilet', frequency: 'daily' },
  { room: 'Up Bathroom', name: 'pick up floor', frequency: 'daily' },
  { room: 'Up Bathroom', name: 'sweep tile', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'Mop tile', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'scrub tub', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'mirir', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'clean off counter', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'wash counter', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'wash sink', frequency: 'weekly' },
  { room: 'Up Bathroom', name: 'Garbage can', frequency: 'weekly' },
  { room: 'Nursery', name: 'floor', frequency: 'daily' },
  { room: 'Nursery', name: 'clean outcrib', frequency: 'weekly' },
  { room: 'Nursery', name: 'wipe crib', frequency: 'weekly' },
  { room: 'Nursery', name: 'vacuume', frequency: 'weekly' },
  { room: 'Nursery', name: 'Clean off dressers', frequency: 'weekly' },
  { room: 'Mom Room', name: 'make bed', frequency: 'daily' },
  { room: 'Mom Room', name: 'pick up floor', frequency: 'daily' },
  { room: 'Mom Room', name: 'pick up dresser', frequency: 'daily' },
  { room: 'Mom Room', name: 'vacuume', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'toilet', frequency: 'daily' },
  { room: 'Mom Bathroom', name: 'pick up floor', frequency: 'daily' },
  { room: 'Mom Bathroom', name: 'sweep tile', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'Mop tile', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'scrub tub', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'scrb shower', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'mirir', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'clean off counter', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'wash counter', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'wash sink', frequency: 'weekly' },
  { room: 'Mom Bathroom', name: 'Garbage can', frequency: 'weekly' },
  { room: 'Mom Closet', name: 'toys', frequency: 'daily' },
  { room: 'Mom Closet', name: 'shoes', frequency: 'daily' },
  { room: 'Mom Closet', name: 'clothes', frequency: 'daily' },
  { room: 'Laundry Room', name: 'Clean off washer', frequency: 'weekly' },
  { room: 'Laundry Room', name: 'Clean off Dryer', frequency: 'weekly' },
  { room: 'Laundry Room', name: 'Sweep Floor', frequency: 'weekly' },
  { room: 'Laundry Room', name: 'Mop floor', frequency: 'weekly' },
  { room: 'Laundry Room', name: 'door knobs', frequency: 'monthly' },
  { room: 'Laundry Room', name: 'light switches', frequency: 'monthly' },
  { room: 'Laundry', name: 'Bring down laundry', frequency: 'daily' },
  { room: 'Laundry', name: 'Start washer', frequency: 'daily' },
  { room: 'Laundry', name: 'move to dryer and start', frequency: 'daily' },
  { room: 'Laundry', name: 'get clothes out of laundry room', frequency: 'daily' },
  { room: 'Laundry', name: 'fold clothes', frequency: 'daily' },
  { room: 'Laundry', name: 'put clothes away', frequency: 'daily' },
  { room: 'Garage', name: 'pick up garbage', frequency: 'daily' },
  { room: 'Outside', name: 'Pick up poop', frequency: 'daily' },
  { room: 'Outside', name: 'long mower', frequency: 'weekly' },
  { room: 'Outside', name: 'clean up Grass', frequency: 'weekly' },
  { room: 'Outside', name: 'front yord', frequency: 'weekly' },
  { room: 'School', name: 'Math', frequency: 'daily' },
  { room: 'School', name: 'History', frequency: 'daily' },
  { room: 'School', name: 'Science', frequency: 'daily' },
  { room: 'School', name: 'reckording', frequency: 'daily' },
  { room: 'School', name: 'piano', frequency: 'daily' },
  { room: 'School', name: 'harp', frequency: 'daily' },
  { room: 'School', name: 'violin', frequency: 'daily' },
  { room: 'Exercise', name: 'Take dog on walk', frequency: 'daily' },
  { room: 'Exercise', name: 'streching', frequency: 'daily' },
  { room: 'Exercise', name: 'active play', frequency: 'daily' },
  { room: 'Exercise', name: 'bascket ball', frequency: 'daily' },
  { room: 'Exercise', name: 'foot ball', frequency: 'daily' },
  { room: 'Exercise', name: 'base ball', frequency: 'daily' },
  { room: 'Exercise', name: 'x box', frequency: 'daily' },
  { room: 'Cars', name: 'Oil change - car', frequency: 'quarterly' },
  { room: 'Cars', name: 'Oil change - van', frequency: 'quarterly' },
  { room: 'Cars', name: 'Check fluids - car', frequency: 'biweekly' },
  { room: 'Cars', name: 'Check fluids - van', frequency: 'biweekly' },
  { room: 'Cars', name: 'Tire pressure - car', frequency: 'monthly' },
  { room: 'Cars', name: 'Tire pressure - van', frequency: 'monthly' },
  { room: 'Cars', name: 'Wash/vacuum car', frequency: 'monthly' },
  { room: 'Cars', name: 'Wash/vacuum van', frequency: 'monthly' },
  { room: 'Cars', name: 'Declutter car', frequency: 'weekly' },
  { room: 'Cars', name: 'Declutter van', frequency: 'weekly' },
  { room: 'Cars', name: 'Rotate tires - car', frequency: 'yearly' },
  { room: 'Cars', name: 'Rotate tires - van', frequency: 'yearly' },
  { room: 'Cars', name: 'Car inspection', frequency: 'yearly' },
  { room: 'Cars', name: 'Van inspection', frequency: 'yearly' },
  { room: 'Cars', name: 'Car insurance renewal', frequency: 'yearly' },
  { room: 'Cars', name: 'Van insurance renewal', frequency: 'yearly' },
  { room: 'Cars', name: 'Register jet ski', frequency: 'yearly' },
  { room: 'Cars', name: 'Insure jet ski', frequency: 'yearly' },
  { room: 'Outside', name: 'Mow lawn', frequency: 'biweekly' },
  { room: 'Outside', name: 'Weed killer', frequency: 'monthly' },
  { room: 'Outside', name: 'Bug killer', frequency: 'monthly' },
  { room: 'Outside', name: 'Fertilizer', frequency: 'quarterly' },
  { room: 'Outside', name: 'Trim bushes', frequency: 'quarterly' },
  { room: 'Outside', name: 'Trim trees', frequency: 'yearly' },
  { room: 'Outside', name: 'Clean gutters', frequency: 'yearly' },
  { room: 'Outside', name: 'Wash windows', frequency: 'yearly' },
  { room: 'Garage', name: 'Sweep/blow garage floor', frequency: 'monthly' },
  { room: 'Garage', name: 'Organize garage storage', frequency: 'quarterly' },
];
